# Generated by Django 5.1 on 2024-09-05 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('product', '0013_alter_brand_id_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_products', to='product.product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_purchased_products', to='product.unit'),
        ),
        migrations.AddField(
            model_name='stock',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_sold_products', to='product.unit'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_alert',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
            preserve_default=False,
        ),
    ]
