# Generated by Django 5.1 on 2024-09-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock_category_stock_product_stock_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
