"""
Django settings for inventoryproject project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import sys


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LEAD_PROJECT_DIR = BASE_DIR / "lead"
if LEAD_PROJECT_DIR.exists():
    sys.path.insert(0, str(LEAD_PROJECT_DIR))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@ujr-e&a%8m%6!z(+ka16+(sm6cug(h6noe%#p%=6%d2nz5t+#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Temporarily enabled to see error details

#ALLOWED_HOSTS = ['anujdeshmukh24.pythonanywhere.com']
ALLOWED_HOSTS = ['www.db-solar.co.in', 'db-solar.co.in', 'localhost', '127.0.0.1', 'testserver']

# Application definition


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}



# Optional: Set token lifetimes
from datetime import timedelta

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
# }


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'dashboard.apps.DashboardConfig',
    'user.apps.UserConfig',
    'customer.apps.CustomerConfig',
    'crispy_forms',
    'crispy_bootstrap4',
    'firereport.apps.FirereportConfig',
    'widget_tweaks',
    'user.group_filters',
    'active_link',
    'generate_barcodes.apps.GenerateBarcodesConfig',
    'detect_barcodes.apps.DetectBarcodesConfig',
    'product.apps.ProductConfig',
    'inventory.apps.InventoryConfig',
    'transactions.apps.TransactionsConfig',
    'quotation.apps.QuotationConfig',
    'homepage.apps.HomepageConfig',
    # CRM (from /lead folder); legacy ``leads`` app removed — use ``manage.py drop_legacy_leads_app`` if tables remain.
    'apps.core.apps.CoreConfig',
    'apps.leads.apps.LeadsConfig',
    'apps.pipeline',
    'apps.surveys',
    'apps.quotations',
    'apps.revenue',
    'apps.analytics',
    'apps.team',
    'apps.settings',
    'apps.control_panel',
    'rest_framework',
    'corsheaders',
    'api.apps.ApiConfig',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.core.middleware.OrganizationMiddleware',
    'user.middleware.CPPermissionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]


ROOT_URLCONF = 'inventoryproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'lead' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventoryproject.wsgi.application'


#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#       #'NAME': #'/home/anujdeshmukh24/DBSolar_19_09_2023/DBSolar_19_09_2023/db.sqlite3',
#        'NAME': BASE_DIR / "db.sqlite3",
#   }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db_solar',
        'USER': 'postgres',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'db_solar',
#         # 'USER': 'root',
#         'PASSWORD': 'Anuj@25032503',
#         'HOST': '',
#         'PORT': '5432',
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'anujdeshmukh24$db',
#         'USER': 'anujdeshmukh24',
#         'PASSWORD': 'Db@275194',
#         'HOST': 'anujdeshmukh24.mysql.pythonanywhere-services.com',
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }





# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Use India timezone for correct local date/time display.
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True

USE_L10N = True

USE_TZ = True


CRISPY_TEMPLATE_PACK = 'bootstrap4'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = (BASE_DIR/"media/")

MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "lead" / "static",
]

STATIC_ROOT = (BASE_DIR/"asert/")


LOGIN_REDIRECT_URL = 'user:post_login_redirect'
#CUSTOMER_URL = 'customer-index'

LOGIN_URL = 'user-login'

# LOGOUT_REDIRECT_URL = '/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'deshmukh.ssd24@gmail.com'
EMAIL_HOST_PASSWORD = 'pesebzcjfrxnuvsg'
PASSWORD_RESET_TIMEOUT = 240
# SESSION_EXPIRE_AT_BROWSER_CLOSE=False
CORS_ALLOW_ALL_ORIGINS = True



# Session expires after 15 minutes of inactivity
SESSION_COOKIE_AGE = 10 * 60   # 15 minutes (in seconds)

# Expire when browser is closed? (optional)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Reset timer each request (so active users stay logged in)
SESSION_SAVE_EVERY_REQUEST = True

