# Generated by Django 3.1.4 on 2024-03-05 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20240304_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('4889996b-00f5-430f-b8d2-f2081983ffc3'), primary_key=True, serialize=False),
        ),
    ]
