# Generated by Django 3.1.4 on 2024-03-05 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20240305_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('fd30aebe-5829-4a39-b382-d9d9d7a8438d'), primary_key=True, serialize=False),
        ),
    ]
