# Generated by Django 3.1.4 on 2024-03-05 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20240305_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('4120b3b0-2264-4936-8ea8-020ffffbace7'), primary_key=True, serialize=False),
        ),
    ]
