# Generated by Django 3.1.4 on 2024-03-05 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20240305_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('a1f8fcdd-5fc2-4675-8b75-14febda33943'), primary_key=True, serialize=False),
        ),
    ]
