# Generated by Django 3.1.4 on 2024-03-06 05:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20240306_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('d27bd53a-c069-41a8-9518-44cc14007779'), primary_key=True, serialize=False),
        ),
    ]
