# Generated by Django 3.1.4 on 2024-03-06 05:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20240306_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('03023acb-6b59-4fc9-803f-a18d376fdccc'), primary_key=True, serialize=False),
        ),
    ]
