# Generated by Django 3.1.4 on 2024-03-06 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20240306_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('3dad91e7-642a-423a-8c2c-4970d7007692'), primary_key=True, serialize=False),
        ),
    ]
