# Generated by Django 3.1.4 on 2024-03-11 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20240306_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('bba4d50a-15f0-49fe-92a3-e23b6a5dde88'), primary_key=True, serialize=False),
        ),
    ]
