# Generated by Django 3.1.4 on 2024-03-11 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20240311_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('620f9b1f-836d-41be-83df-b8161f5d60bd'), primary_key=True, serialize=False),
        ),
    ]
