# Generated by Django 3.1.4 on 2024-03-11 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20240311_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('375f186c-d793-4b27-9973-5634dc6528ad'), primary_key=True, serialize=False),
        ),
    ]
