# Generated by Django 3.1.4 on 2024-03-14 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20240314_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('109d0636-f8f3-4b57-9521-c798d2112fd1'), primary_key=True, serialize=False),
        ),
    ]
