# Generated by Django 3.1.4 on 2024-03-22 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20240322_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('225c16d2-c946-4f0d-a275-9d49e0be3435'), primary_key=True, serialize=False),
        ),
    ]
