# Generated by Django 3.1.4 on 2024-03-22 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_auto_20240322_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('b641ac2b-c346-425d-8394-6966dda94c75'), primary_key=True, serialize=False),
        ),
    ]
