# Generated by Django 3.1.4 on 2024-03-22 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_auto_20240322_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('2d6c99f8-3058-4f33-ad97-05289a40303d'), primary_key=True, serialize=False),
        ),
    ]
