# Generated by Django 3.1.4 on 2024-03-22 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_auto_20240322_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('e42d9d1a-171f-4974-8bac-29878c773100'), primary_key=True, serialize=False),
        ),
    ]
