# Generated by Django 3.1.4 on 2024-03-22 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_auto_20240322_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('ae5b5fc2-4f04-4830-8adf-8738649b048a'), primary_key=True, serialize=False),
        ),
    ]
