# Generated by Django 3.1.4 on 2024-03-22 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_auto_20240322_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('65709eb8-38f3-4adc-845d-f45f0c78efa1'), primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Meters',
        ),
    ]
