# Generated by Django 3.1.4 on 2024-03-23 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_auto_20240322_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('d2b654d0-8f8e-4fb0-8090-6ccb652ee91c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meters',
            name='capacity',
            field=models.CharField(max_length=50),
        ),
    ]
