# Generated by Django 3.1.4 on 2024-03-23 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_auto_20240323_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('54f08978-3ae1-4e56-82f0-1c4f3a2eb093'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generationct',
            name='capacity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='generationmeter',
            name='capacity',
            field=models.CharField(max_length=50),
        ),
    ]
