# Generated by Django 3.1.4 on 2024-03-26 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_auto_20240323_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('e0f87b1e-dab3-44a9-ba72-2d93ea696569'), primary_key=True, serialize=False),
        ),
    ]
