# Generated by Django 3.1.4 on 2024-03-28 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_auto_20240326_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationmeter',
            name='CT_capacity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generationmeter',
            name='CT_make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generationmeter',
            name='CT_serial_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('ec53569e-324e-461f-be30-8ca891e974b6'), primary_key=True, serialize=False),
        ),
    ]
