# Generated by Django 3.1.4 on 2024-03-30 11:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_auto_20240328_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('bb549bd9-8034-481c-98af-ccf8c1b3b394'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MSEB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=100)),
                ('load_extension', models.BooleanField(default=False)),
                ('flisibility', models.BooleanField(default=False)),
                ('quotation', models.BooleanField(default=False)),
                ('sent_to_bill', models.BooleanField(default=False)),
                ('net_meter', models.BooleanField(default=False)),
                ('flexibility', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
                ('meter_testing', models.BooleanField(default=False)),
                ('agreement', models.BooleanField(default=False)),
                ('release', models.BooleanField(default=False)),
                ('installation_date', models.BooleanField(default=False)),
                ('load_extension_date', models.DateTimeField(auto_now_add=True)),
                ('flisibility_date', models.DateTimeField(auto_now_add=True)),
                ('quotation_date', models.DateTimeField(auto_now_add=True)),
                ('sent_to_bill_date', models.DateTimeField(auto_now_add=True)),
                ('net_meter_date', models.DateTimeField(auto_now_add=True)),
                ('flexibility_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('meter_testing_date', models.DateTimeField(auto_now_add=True)),
                ('agreement_date', models.DateTimeField(auto_now_add=True)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('installation_date_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
