# Generated by Django 3.1.4 on 2024-03-30 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_auto_20240330_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mseb',
            name='customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('9772ca07-65d2-4721-bdb6-bdc4f48c63e4'), primary_key=True, serialize=False),
        ),
    ]
