# Generated by Django 3.1.4 on 2024-03-31 04:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_auto_20240331_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mseb',
            name='customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('3e01158d-29c7-4b53-8792-c87d1f0bcfc0'), primary_key=True, serialize=False),
        ),
    ]
