# Generated by Django 3.1.4 on 2024-03-31 04:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_auto_20240331_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('41246d5c-b273-4ad2-9d90-8620bb01ddae'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='agreement',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='agreement_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='approval',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='approval_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='flexibility',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='flexibility_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='flisibility',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='flisibility_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='installation_date',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='installation_date_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='load_extension',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='load_extension_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='meter_testing',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='meter_testing_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='net_meter',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='net_meter_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='quotation',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='quotation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='release',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='release_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='sent_to_bill',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='sent_to_bill_date',
            field=models.DateTimeField(),
        ),
    ]
