# Generated by Django 3.1.4 on 2024-03-31 04:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0043_auto_20240331_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('d73959d9-d945-4f38-86da-822efac63355'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='flexibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='flisibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='installation_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='load_extension',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='meter_testing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='net_meter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='quotation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='release',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='sent_to_bill',
            field=models.BooleanField(default=False),
        ),
    ]
