# Generated by Django 3.1.4 on 2024-03-31 04:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_auto_20240331_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('ce8274c4-f08a-4b3a-b2a7-72a33a98a033'), primary_key=True, serialize=False),
        ),
    ]
