# Generated by Django 3.1.4 on 2024-03-31 04:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_auto_20240331_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('46aa369d-5a39-40ae-a976-d7d2db77c6ec'), primary_key=True, serialize=False),
        ),
    ]
