# Generated by Django 3.1.4 on 2024-03-31 05:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_auto_20240331_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('8740f065-444e-477a-b5d6-d0fc02f39e65'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='agreement_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='approval_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='flexibility_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='flisibility_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='installation_date_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='load_extension_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='meter_testing_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='net_meter_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='quotation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='sent_to_bill_date',
            field=models.DateTimeField(null=True),
        ),
    ]
