# Generated by Django 3.1.4 on 2024-04-05 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0047_auto_20240331_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationmeter',
            name='AssignBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_meters_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meters',
            name='AssignBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meters_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('008fd4a7-21da-41ec-b472-6059269cb50c'), primary_key=True, serialize=False),
        ),
    ]
