# Generated by Django 3.1.4 on 2024-04-11 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0049_auto_20240409_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='mseb',
            name='AssignBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MSEB_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('45f12343-f545-4f0a-a85f-5d95f32446b7'), primary_key=True, serialize=False),
        ),
    ]
