# Generated by Django 3.1.4 on 2024-05-12 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_auto_20240411_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('df9038b4-25b5-486e-9bc9-3dc1625a688b'), primary_key=True, serialize=False),
        ),
    ]
