# Generated by Django 3.1.4 on 2024-05-29 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0053_auto_20240527_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('70a45c9e-49ef-42d3-bfb6-8fcfc4c7b16d'), primary_key=True, serialize=False),
        ),
    ]
