# Generated by Django 3.1.4 on 2024-05-29 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0054_auto_20240529_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('90ee9631-4157-49d9-a1c6-98efcde33722'), primary_key=True, serialize=False),
        ),
    ]
