# Generated by Django 3.1.4 on 2024-05-29 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0055_auto_20240529_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('1f30b4cb-aee9-4d00-ad24-353f0dfb40a8'), primary_key=True, serialize=False),
        ),
    ]
