# Generated by Django 3.1.4 on 2024-08-07 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0060_auto_20240807_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('086a1b1f-3b0a-4c15-9063-26fde75035ce'), primary_key=True, serialize=False),
        ),
    ]
