# Generated by Django 3.1.4 on 2024-08-07 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0061_auto_20240807_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('72c1eda7-970e-4e28-bcd2-36f45bb3c168'), primary_key=True, serialize=False),
        ),
    ]
