# Generated by Django 3.1.4 on 2024-08-16 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0063_auto_20240807_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('e41324c4-d2b2-486d-915f-8d6bf9758f9a'), primary_key=True, serialize=False),
        ),
    ]
