[phases.setup]
nixPkgs = [
  "python310",
  "libxml2",
  "libxslt",
  "gcc",
  "zlib",
  "freetype",
  "libjpeg",
  "tesseract"
]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel"
]
