# Generated by Django 5.1.3 on 2025-10-26 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamName", models.CharField(max_length=200, null=True)),
                ("teamLeaderName", models.CharField(max_length=250, null=True)),
                ("teamLeadMobno", models.CharField(max_length=15, null=True)),
                ("teamMembers", models.CharField(max_length=300, null=True)),
                ("postingDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Firereport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.CharField(max_length=250, null=True)),
                ("MobileNumber", models.CharField(max_length=12, null=True)),
                ("Location", models.CharField(max_length=200, null=True)),
                ("Message", models.CharField(max_length=200, null=True)),
                ("Status", models.CharField(max_length=150, null=True)),
                ("Postingdate", models.DateTimeField(auto_now_add=True)),
                ("AssignedTime", models.CharField(max_length=150, null=True)),
                ("UpdationDate", models.DateTimeField(null=True)),
                ("Account_id", models.IntegerField(default=0)),
                ("AssignBy", models.IntegerField(default=0)),
                (
                    "AssignTo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Firetequesthistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=200, null=True)),
                ("remark", models.CharField(max_length=250, null=True)),
                ("postingDate", models.DateTimeField(auto_now_add=True)),
                ("AssignBy", models.IntegerField(default=0)),
                (
                    "AssignTo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firereport",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firereport.firereport",
                    ),
                ),
            ],
        ),
    ]
