# Generated by Django 5.2.10 on 2026-01-21 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='firereport',
            name='Account_id',
            field=models.IntegerField(db_column='account_id', default=0),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='AssignBy',
            field=models.IntegerField(db_column='assignby', default=0),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='AssignTo',
            field=models.ForeignKey(db_column='assignto_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='AssignedTime',
            field=models.CharField(db_column='assignedtime', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='FullName',
            field=models.CharField(db_column='fullname', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='Location',
            field=models.CharField(db_column='Location', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='Message',
            field=models.CharField(db_column='message', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='MobileNumber',
            field=models.CharField(db_column='mobilenumber', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='Postingdate',
            field=models.DateTimeField(auto_now_add=True, db_column='postingdate'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='Status',
            field=models.CharField(db_column='status', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='UpdationDate',
            field=models.DateTimeField(db_column='updationdate', null=True),
        ),
        migrations.AlterField(
            model_name='firetequesthistory',
            name='AssignTo',
            field=models.ForeignKey(db_column='assignto_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
