# Generated by Django 5.2.10 on 2026-01-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0002_alter_firereport_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firereport',
            name='Message',
            field=models.TextField(db_column='message', null=True),
        ),
    ]
