# Generated by Django 5.2.10 on 2026-01-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0004_fix_firereport_id_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firereport',
            name='Status',
            field=models.CharField(db_column='status', default='Pending', max_length=150, null=True),
        ),
    ]
