# Generated by Django 5.2.10 on 2026-01-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0006_backfill_pending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firereport',
            name='Status',
            field=models.CharField(blank=True, db_column='status', default='Pending', max_length=150, null=True),
        ),
    ]
