# Generated by Django 5.2.10 on 2026-01-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0007_alter_firereport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firetequesthistory',
            name='postingDate',
            field=models.DateTimeField(auto_now_add=True, db_column='postingdate'),
        ),
    ]
