# Generated by Django 5.2.10 on 2026-01-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0010_alter_firetequesthistory_postingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firetequesthistory',
            name='postingDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
