# Generated by Django 5.2.10 on 2026-01-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0012_convert_date_fields_to_datetime'),
    ]

    operations = [
        # The database column 'assignby' already exists, we're just updating Django's model state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database changes needed - column already exists with correct name
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='firetequesthistory',
                    name='AssignBy',
                    field=models.IntegerField(db_column='assignby', default=0),
                ),
            ],
        ),
    ]
