# Generated by Django 5.2.10 on 2026-01-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0014_fix_firetequesthistory_id_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firetequesthistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
