# Generated by Django 5.1.3 on 2025-10-26 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200, null=True)),
                ("phone", models.CharField(max_length=50, null=True)),
                ("DOB", models.DateField(null=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Administration", "Administration"),
                            ("Stockist", "Stockist"),
                            ("Engineers", "Engineers"),
                            ("Finance", "Finance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="profile_images/default.png",
                        null=True,
                        upload_to="profile_pics",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Sr.Cleark", "Sr.Cleark"),
                            ("Jr.Cleark", "Jr.Cleark"),
                            ("Accountant", "Accountant"),
                            ("Sr.Engg", "Sr.Engg"),
                            ("Jr.Engg", "Jr.Engg"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("last_updated_by", models.PositiveIntegerField(null=True)),
                ("workphone", models.CharField(max_length=50, null=True)),
                (
                    "bg",
                    models.CharField(
                        choices=[
                            ("O +ve", "O +ve"),
                            ("O -ve", "O -ve"),
                            ("A +ve", "A +ve"),
                            ("A -ve", "A -ve"),
                            ("B +ve", "B +ve"),
                            ("B -ve", "B -ve"),
                            ("AB +ve", "AB +ve"),
                            ("AB -ve", "AB -ve"),
                        ],
                        max_length=50,
                    ),
                ),
                ("city", models.CharField(max_length=50, null=True)),
                ("taluka", models.CharField(max_length=50, null=True)),
                ("district", models.CharField(max_length=50, null=True)),
                ("pg", models.CharField(max_length=50, null=True)),
                ("institution", models.CharField(max_length=50, null=True)),
                ("yop", models.DateField(null=True)),
                ("specili", models.CharField(max_length=50, null=True)),
                ("resign_reason", models.CharField(max_length=150, null=True)),
                ("resign_type", models.CharField(max_length=50, null=True)),
                ("resign_date", models.DateField(null=True)),
                ("rejoin_reason", models.CharField(max_length=150, null=True)),
                ("rejoin_date", models.DateField(null=True)),
                ("name", models.CharField(max_length=50, null=True)),
                ("email", models.CharField(max_length=50, null=True)),
                ("emraddress", models.CharField(max_length=50, null=True)),
                (
                    "customer",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, to="auth.permission"),
                ),
            ],
        ),
    ]
