# Generated by Django 5.2.10 on 2026-01-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(db_column='dob', null=True),
        ),
    ]
