# Generated by GPT for control-panel permission tables on 2026-01-24

from django.db import migrations


def create_tables_if_missing(apps, schema_editor):
    """
    Ensure the control-panel permission tables exist.

    This project has legacy tables like `user_modulepermission` with a different
    schema. The current control-panel permission system uses dedicated tables:
      - user_cp_module
      - user_cp_modulepermission
      - user_cp_usermodulepermission

    We create them idempotently if they don't exist.
    """

    existing = set(schema_editor.connection.introspection.table_names())

    Module = apps.get_model("user", "Module")
    ModulePermission = apps.get_model("user", "ModulePermission")
    UserModulePermission = apps.get_model("user", "UserModulePermission")

    # Create in FK dependency order
    if Module._meta.db_table not in existing:
        schema_editor.create_model(Module)
        existing.add(Module._meta.db_table)

    if ModulePermission._meta.db_table not in existing:
        schema_editor.create_model(ModulePermission)
        existing.add(ModulePermission._meta.db_table)

    if UserModulePermission._meta.db_table not in existing:
        schema_editor.create_model(UserModulePermission)
        existing.add(UserModulePermission._meta.db_table)


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_repair_controlpanelaccess_columns"),
    ]

    operations = [
        migrations.RunPython(create_tables_if_missing, reverse_code=migrations.RunPython.noop),
    ]

