# Generated by Django 5.2.10 on 2026-01-24 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_create_control_panel_permission_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_cp_module',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='CPModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('add', 'Add'), ('view', 'View'), ('edit', 'Edit'), ('delete', 'Delete'), ('export', 'Export'), ('import', 'Import'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='user.cpmodule')),
            ],
            options={
                'db_table': 'user_cp_modulepermission',
                'ordering': ['module', 'order', 'operation'],
                'unique_together': {('module', 'operation')},
            },
        ),
        migrations.CreateModel(
            name='CPUserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('module_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='user.cpmodulepermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_module_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_cp_usermodulepermission',
                'ordering': ['user', 'module_permission__module', 'module_permission__operation'],
                'unique_together': {('user', 'module_permission')},
            },
        ),
    ]
