# Generated by Django 5.2.10 on 2026-01-24 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_purchaseserial_serialno'),
        ('user', '0007_cp_permission_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_account', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_account', to='transactions.vendor')),
            ],
        ),
    ]
