# Generated by Django 5.2.10 on 2026-01-24 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_vendor_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_cp_portal',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='CPPortalModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portals', to='user.cpmodule')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_modules', to='user.cpportal')),
            ],
            options={
                'db_table': 'user_cp_portal_module',
                'ordering': ['portal', 'order', 'module__display_name'],
                'unique_together': {('portal', 'module')},
            },
        ),
        migrations.CreateModel(
            name='CPUserPortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_portal_grants', to=settings.AUTH_USER_MODEL)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='user.cpportal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_portal_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_cp_userportalaccess',
                'ordering': ['user', 'portal'],
                'unique_together': {('user', 'portal')},
            },
        ),
    ]
