# Generated by GPT on 2026-01-24

from django.db import migrations


def fix_auth_user_id_sequence(apps, schema_editor):
    """
    Some databases in this project have `auth_user.id` without a DEFAULT/sequence,
    which breaks creating new users (id becomes NULL).

    This migration repairs the sequence + default for PostgreSQL.
    """

    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        # Create sequence if missing
        cursor.execute(
            """
            DO $$
            BEGIN
              IF NOT EXISTS (
                SELECT 1 FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE c.relkind = 'S'
                  AND c.relname = 'auth_user_id_seq'
              ) THEN
                CREATE SEQUENCE auth_user_id_seq;
              END IF;
            END
            $$;
            """
        )

        # Ensure column default uses the sequence
        cursor.execute(
            "ALTER TABLE auth_user ALTER COLUMN id SET DEFAULT nextval('auth_user_id_seq');"
        )

        # Set sequence to max(id)
        cursor.execute(
            "SELECT setval('auth_user_id_seq', COALESCE((SELECT MAX(id) FROM auth_user), 1), true);"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_portals"),
    ]

    operations = [
        migrations.RunPython(fix_auth_user_id_sequence, reverse_code=migrations.RunPython.noop),
    ]

