# Generated by GPT on 2026-01-24

from django.db import migrations


def fix_user_profile_id_sequence(apps, schema_editor):
    """
    Repair missing DEFAULT/sequence for `user_profile.id`.
    This is required because a post_save signal auto-creates Profile rows.
    """

    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            DO $$
            BEGIN
              IF NOT EXISTS (
                SELECT 1 FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE c.relkind = 'S'
                  AND c.relname = 'user_profile_id_seq'
              ) THEN
                CREATE SEQUENCE user_profile_id_seq;
              END IF;
            END
            $$;
            """
        )
        cursor.execute(
            "ALTER TABLE user_profile ALTER COLUMN id SET DEFAULT nextval('user_profile_id_seq');"
        )
        cursor.execute(
            "SELECT setval('user_profile_id_seq', COALESCE((SELECT MAX(id) FROM user_profile), 1), true);"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_fix_auth_user_id_sequence"),
    ]

    operations = [
        migrations.RunPython(fix_user_profile_id_sequence, reverse_code=migrations.RunPython.noop),
    ]

