# Generated by GPT on 2026-01-24

from django.db import migrations


def fix_auth_group_id_sequence(apps, schema_editor):
    """
    Repair missing DEFAULT/sequence for `auth_group.id`.
    Required because vendor login creation uses Group.get_or_create().
    """

    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            DO $$
            BEGIN
              IF NOT EXISTS (
                SELECT 1 FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE c.relkind = 'S'
                  AND c.relname = 'auth_group_id_seq'
              ) THEN
                CREATE SEQUENCE auth_group_id_seq;
              END IF;
            END
            $$;
            """
        )
        cursor.execute(
            "ALTER TABLE auth_group ALTER COLUMN id SET DEFAULT nextval('auth_group_id_seq');"
        )
        cursor.execute(
            "SELECT setval('auth_group_id_seq', COALESCE((SELECT MAX(id) FROM auth_group), 1), true);"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_fix_user_profile_id_sequence"),
    ]

    operations = [
        migrations.RunPython(fix_auth_group_id_sequence, reverse_code=migrations.RunPython.noop),
    ]

