# Generated by Django 5.2.10 on 2026-01-25 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_fix_auth_group_id_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPNavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, unique=True)),
                ('section', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=150)),
                ('url_name', models.CharField(blank=True, default='', max_length=150)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='user.cpportal')),
            ],
            options={
                'db_table': 'user_cp_navitem',
                'ordering': ['portal__order', 'section', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CPUserNavAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_nav_grants', to=settings.AUTH_USER_MODEL)),
                ('nav_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='user.cpnavitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_nav_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_cp_usernavaccess',
                'ordering': ['user', 'nav_item'],
                'unique_together': {('user', 'nav_item')},
            },
        ),
    ]
