# Generated by Django 5.2.10 on 2026-03-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_cpnavitem_cpusernavaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('Administration', 'Administration'), ('Stockist', 'Stockist'), ('Engineers', 'Engineers'), ('Finance', 'Finance'), ('Associate', 'Associate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Sr.Cleark', 'Sr.Cleark'), ('Jr.Cleark', 'Jr.Cleark'), ('Accountant', 'Accountant'), ('Sr.Engg', 'Sr.Engg'), ('Jr.Engg', 'Jr.Engg'), ('Associate', 'Associate')], max_length=50, null=True),
        ),
    ]
