# Generated by Django 5.1.3 on 2025-10-26 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("inventory", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseBill",
            fields=[
                ("billno", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FinalSale",
            fields=[
                ("billno", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("update_time", models.DateTimeField(null=True)),
                ("return_bill", models.BooleanField(default=False)),
                ("return_date", models.DateTimeField(null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_sales",
                        to="customer.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalBillDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eway", models.CharField(blank=True, max_length=50, null=True)),
                ("veh", models.CharField(blank=True, max_length=50, null=True)),
                ("destination", models.CharField(blank=True, max_length=50, null=True)),
                ("po", models.CharField(blank=True, max_length=255, null=True)),
                ("cgst", models.CharField(blank=True, max_length=50, null=True)),
                ("sgst", models.CharField(blank=True, max_length=50, null=True)),
                ("igst", models.CharField(blank=True, max_length=50, null=True)),
                ("cess", models.CharField(blank=True, max_length=50, null=True)),
                ("tcs", models.CharField(blank=True, max_length=50, null=True)),
                ("total", models.CharField(blank=True, max_length=50, null=True)),
                ("gst_value", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "final_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "round_off",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "billno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finaldetailsbillno",
                        to="transactions.finalsale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalSaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "r_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "final_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "final_bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_sale_items",
                        to="transactions.finalsale",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_sale_stock",
                        to="inventory.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseBillDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eway", models.CharField(blank=True, max_length=50, null=True)),
                ("veh", models.CharField(blank=True, max_length=50, null=True)),
                ("destination", models.CharField(blank=True, max_length=50, null=True)),
                ("po", models.CharField(blank=True, max_length=255, null=True)),
                ("cgst", models.CharField(blank=True, max_length=50, null=True)),
                ("sgst", models.CharField(blank=True, max_length=50, null=True)),
                ("igst", models.CharField(blank=True, max_length=50, null=True)),
                ("cess", models.CharField(blank=True, max_length=50, null=True)),
                ("tcs", models.CharField(blank=True, max_length=50, null=True)),
                ("total", models.CharField(blank=True, max_length=50, null=True)),
                ("gst_value", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "final_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "round_off",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "delivery_charges",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "billno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchasedetailsbillno",
                        to="transactions.purchasebill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                (
                    "perprice",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "totalprice",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "billno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchasebillno",
                        to="transactions.purchasebill",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchaseitem_purchased_products",
                        to="product.unit",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchaseitem",
                        to="inventory.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnSale",
            fields=[
                ("billno", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("update_time", models.DateTimeField(null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_sales",
                        to="customer.customer",
                    ),
                ),
                (
                    "final_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_sales",
                        to="transactions.finalsale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnBillDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eway", models.CharField(blank=True, max_length=50, null=True)),
                ("veh", models.CharField(blank=True, max_length=50, null=True)),
                ("destination", models.CharField(blank=True, max_length=50, null=True)),
                ("po", models.CharField(blank=True, max_length=255, null=True)),
                ("cgst", models.CharField(blank=True, max_length=50, null=True)),
                ("sgst", models.CharField(blank=True, max_length=50, null=True)),
                ("igst", models.CharField(blank=True, max_length=50, null=True)),
                ("cess", models.CharField(blank=True, max_length=50, null=True)),
                ("tcs", models.CharField(blank=True, max_length=50, null=True)),
                ("total", models.CharField(blank=True, max_length=50, null=True)),
                ("gst_value", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "final_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "round_off",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "final_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_bill_details",
                        to="transactions.finalsale",
                    ),
                ),
                (
                    "billno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returndetailsbillno",
                        to="transactions.returnsale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnSaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "r_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "final_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "final_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_finalbill_items",
                        to="transactions.finalsale",
                    ),
                ),
                (
                    "return_bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_sale_items",
                        to="transactions.returnsale",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_sale_stock",
                        to="inventory.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleBill",
            fields=[
                ("billno", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=12)),
                ("address", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("gstin", models.CharField(max_length=15)),
                ("update_time", models.DateTimeField(null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "Cust_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salescustomer",
                        to="customer.customer",
                    ),
                ),
                (
                    "final_salebill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_bills",
                        to="transactions.finalsale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseSerial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serialNo", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "billno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_serials",
                        to="transactions.purchasebill",
                    ),
                ),
                (
                    "final_salebill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_bills1",
                        to="transactions.finalsale",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchaseserial_set",
                        to="transactions.purchaseitem",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchaseserial_purchases",
                        to="product.unit",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_serials",
                        to="inventory.stock",
                    ),
                ),
                (
                    "return_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_bills",
                        to="transactions.returnsale",
                    ),
                ),
                (
                    "sales_billno",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_bill",
                        to="transactions.salebill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleBillDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eway", models.CharField(blank=True, max_length=50, null=True)),
                ("veh", models.CharField(blank=True, max_length=50, null=True)),
                ("destination", models.CharField(blank=True, max_length=50, null=True)),
                ("po", models.CharField(blank=True, max_length=255, null=True)),
                ("cgst", models.CharField(blank=True, max_length=50, null=True)),
                ("sgst", models.CharField(blank=True, max_length=50, null=True)),
                ("igst", models.CharField(blank=True, max_length=50, null=True)),
                ("cess", models.CharField(blank=True, max_length=50, null=True)),
                ("tcs", models.CharField(blank=True, max_length=50, null=True)),
                ("total", models.CharField(blank=True, max_length=50, null=True)),
                ("gst_value", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "final_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "round_off",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "billno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saledetailsbillno",
                        to="transactions.salebill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                ("perprice", models.IntegerField(default=1)),
                ("totalprice", models.IntegerField(default=1)),
                (
                    "r_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "total_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "billno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salebillno",
                        to="transactions.salebill",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saleitem_saled_products",
                        to="product.unit",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saleitem",
                        to="inventory.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("phone", models.CharField(max_length=12, unique=True)),
                ("address", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("gstin", models.CharField(max_length=15, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "supplier_id",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("contact_person", models.CharField(max_length=100, null=True)),
                ("city", models.CharField(max_length=50, null=True)),
                ("state", models.CharField(max_length=50, null=True)),
                ("post_code", models.CharField(max_length=10, null=True)),
                ("status", models.BooleanField(default=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_suppliers",
                        to="product.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="purchasebill",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchasesupplier",
                to="transactions.supplier",
            ),
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("phone", models.CharField(max_length=12, unique=True)),
                ("address", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "gstin",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("vendor_id", models.CharField(blank=True, max_length=20, unique=True)),
                ("contact_person", models.CharField(max_length=100, null=True)),
                ("city", models.CharField(max_length=50, null=True)),
                ("state", models.CharField(max_length=50, null=True)),
                ("post_code", models.CharField(max_length=10, null=True)),
                ("status", models.BooleanField(default=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_vendor",
                        to="product.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="salebill",
            name="Vend_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salesvendor",
                to="transactions.vendor",
            ),
        ),
        migrations.AddField(
            model_name="returnsale",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_vendor",
                to="transactions.vendor",
            ),
        ),
        migrations.AddField(
            model_name="finalsale",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="final_sales_vendor",
                to="transactions.vendor",
            ),
        ),
    ]
