# Generated by Django 3.1.4 on 2024-03-04 17:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('adbfcfba-74d5-48a9-8c85-e81eca6bcdc7'), primary_key=True, serialize=False),
        ),
    ]
