# Generated by Django 3.1.4 on 2024-03-05 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20240305_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('65e34001-4565-4eee-a1c4-f780d3cc3857'), primary_key=True, serialize=False),
        ),
    ]
