# Generated by Django 3.1.4 on 2024-03-05 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20240305_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('8c792f56-8a3c-41ce-a56c-040f280a2ae1'), primary_key=True, serialize=False),
        ),
    ]
