# Generated by Django 3.1.4 on 2024-03-06 04:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20240305_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('0a455452-2321-4f51-86cb-612fd707624d'), primary_key=True, serialize=False),
        ),
    ]
