# Generated by Django 3.1.4 on 2024-03-06 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20240306_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('c60d6916-21b6-434d-a04c-f88ae3550499'), primary_key=True, serialize=False),
        ),
    ]
