# Generated by Django 3.1.4 on 2024-03-06 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20240306_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('19b1005e-5ea3-429a-9575-87ce43f5ca87'), primary_key=True, serialize=False),
        ),
    ]
