# Generated by Django 3.1.4 on 2024-03-06 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20240306_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('c39aa1ae-b902-434e-818d-effc81438190'), primary_key=True, serialize=False),
        ),
    ]
