# Generated by Django 3.1.4 on 2024-03-14 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20240311_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('56546429-9e29-4ecc-bf74-d36edbcdb40a'), primary_key=True, serialize=False),
        ),
    ]
