# Generated by Django 3.1.4 on 2024-03-14 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20240314_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('9793bd0e-2cdd-4b2b-ba48-221911eec7ea'), primary_key=True, serialize=False),
        ),
    ]
