# Generated by Django 3.1.4 on 2024-03-22 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20240314_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('366aa09e-99b9-4199-8067-bf24e5c9f712'), primary_key=True, serialize=False),
        ),
    ]
