# Generated by Django 3.1.4 on 2024-03-22 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_auto_20240322_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('f4b6ef54-57ac-453a-8270-80945393a6bd'), primary_key=True, serialize=False),
        ),
    ]
