# Generated by Django 3.1.4 on 2024-03-22 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_auto_20240322_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('a4729e77-a432-4765-84ed-fd8ece0da570'), primary_key=True, serialize=False),
        ),
    ]
