# Generated by Django 3.1.4 on 2024-03-22 14:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_auto_20240322_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('c4d63c8b-fa30-40d6-bfa1-b9524eddce96'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Meters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('serial_no', models.CharField(max_length=20)),
                ('transformer_type', models.CharField(max_length=50)),
                ('meter_type', models.CharField(max_length=50)),
                ('transformer_make', models.CharField(max_length=255)),
                ('transformer_capacity', models.CharField(max_length=255)),
                ('transformer_serial_number', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='customer.customer')),
            ],
        ),
    ]
