# Generated by Django 3.1.4 on 2024-03-22 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_auto_20240322_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('81c5c5d1-6906-4b1b-af57-fb06072ff646'), primary_key=True, serialize=False),
        ),
    ]
