# Generated by Django 3.1.4 on 2024-03-22 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_auto_20240322_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('dbe55101-234a-4578-b46b-d0464212c6a6'), primary_key=True, serialize=False),
        ),
    ]
