# Generated by Django 3.1.4 on 2024-03-22 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_auto_20240322_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('37a2d1c1-baf7-4dee-aba0-ccb5b9a8a230'), primary_key=True, serialize=False),
        ),
    ]
