# Generated by Django 3.1.4 on 2024-03-31 04:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_auto_20240330_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='mseb',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('3fc32028-baf9-488a-af9c-7e370a4a3d89'), primary_key=True, serialize=False),
        ),
    ]
