# Generated by Django 3.1.4 on 2024-04-09 11:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0048_auto_20240405_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='mseb',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mseb_data', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('4fc379fe-d769-446d-b42d-2fba126a4c18'), primary_key=True, serialize=False),
        ),
    ]
