# Generated by Django 3.1.4 on 2024-04-11 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_auto_20240411_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='com_warranty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='inv_warranty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sol_warranty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('04977979-2001-4db9-a5f6-ca99b5ee4b46'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_load',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
