# Generated by Django 3.1.4 on 2024-05-27 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0052_auto_20240512_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('2588d8ac-9dd3-44ce-b309-d62ac8698da3'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='InspectionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(null=True)),
                ('solar_Module_Completed', models.BooleanField(default=False)),
                ('solar_Module_Reason', models.CharField(blank=True, max_length=255, null=True)),
                ('solar_Module_Reason_other', models.CharField(blank=True, max_length=255, null=True)),
                ('inverter_Completed', models.BooleanField(default=False)),
                ('inverter_Reason', models.CharField(blank=True, max_length=255, null=True)),
                ('inverter_Reason_other', models.CharField(blank=True, max_length=255, null=True)),
                ('net_Meter_Completed', models.BooleanField(default=False)),
                ('net_Meter_Reason', models.CharField(blank=True, max_length=255, null=True)),
                ('net_Meter_Reason_other', models.CharField(blank=True, max_length=255, null=True)),
                ('ct_Completed', models.BooleanField(default=False)),
                ('ct_Reason', models.CharField(blank=True, max_length=255, null=True)),
                ('ct_Checkmark_other', models.CharField(blank=True, max_length=255, null=True)),
                ('generation_Meters_Completed', models.BooleanField(default=False)),
                ('generation_Meters_Reason', models.CharField(blank=True, max_length=255, null=True)),
                ('generation_Meters_Reason_other', models.CharField(blank=True, max_length=255, null=True)),
                ('gen_CT_Meters_Completed', models.BooleanField(default=False)),
                ('gen_CT_Meters_Reason', models.CharField(blank=True, max_length=255, null=True)),
                ('gen_CT_Meters_Reason_other', models.CharField(blank=True, max_length=255, null=True)),
                ('ac_Panel_Cabling_Completed', models.BooleanField(default=False)),
                ('ac_Panel_Cabling_Reason', models.CharField(blank=True, max_length=255, null=True)),
                ('ac_Panel_Cabling_Reason_other', models.CharField(blank=True, max_length=255, null=True)),
                ('dc_Panel_Cabling_Completed', models.BooleanField(default=False)),
                ('dc_Panel_Cabling_Reason', models.CharField(blank=True, max_length=255, null=True)),
                ('dc_Panel_Cabling_Reason_other', models.CharField(blank=True, max_length=255, null=True)),
                ('fabrication_Completed', models.BooleanField(default=False)),
                ('fabrication_Reason', models.CharField(blank=True, max_length=255, null=True)),
                ('fabrication_Reason_other', models.CharField(blank=True, max_length=255, null=True)),
                ('walkway_Completed', models.BooleanField(default=False)),
                ('walkway_Reason', models.CharField(blank=True, max_length=255, null=True)),
                ('walkway_Reason_other', models.CharField(blank=True, max_length=255, null=True)),
                ('pipeline_Completed', models.BooleanField(default=False)),
                ('pipeline_Reason', models.CharField(blank=True, max_length=255, null=True)),
                ('pipeline_Reason_other', models.CharField(blank=True, max_length=255, null=True)),
                ('ropeway_Completed', models.BooleanField(default=False)),
                ('ropeway_Reason', models.CharField(blank=True, max_length=255, null=True)),
                ('ropeway_Reason_other', models.CharField(blank=True, max_length=255, null=True)),
                ('rolling_Completed', models.BooleanField(default=False)),
                ('rolling_Reason', models.CharField(blank=True, max_length=255, null=True)),
                ('rolling_Reason_other', models.CharField(blank=True, max_length=255, null=True)),
                ('overall_Details', models.TextField(blank=True, null=True)),
                ('info_Correct', models.BooleanField(default=False)),
                ('AssignBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='customer.customer')),
            ],
        ),
    ]
