# Generated by Django 3.1.4 on 2024-05-30 04:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0056_auto_20240529_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('9371b377-17c6-4d01-b43f-9182b9433956'), primary_key=True, serialize=False),
        ),
    ]
