# Generated by Django 3.1.4 on 2024-06-15 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0057_auto_20240530_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('f7f4e6e5-9563-45a9-b738-193e075d7c8c'), primary_key=True, serialize=False),
        ),
    ]
