# Generated by Django 3.1.4 on 2024-06-16 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0058_auto_20240615_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('1dce9375-f4f0-42af-9cff-bea6f037fd83'), primary_key=True, serialize=False),
        ),
    ]
