# Generated by Django 3.1.4 on 2024-08-07 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0059_auto_20240616_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('9f1b36cf-85df-41a6-80ce-b5162c3cff18'), primary_key=True, serialize=False),
        ),
    ]
