# Generated by Django 3.1.4 on 2024-08-07 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0062_auto_20240807_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('0915c3fd-a0ea-45f0-bee7-93ac13337eec'), primary_key=True, serialize=False),
        ),
    ]
