# Generated by Django 3.1.4 on 2024-08-16 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0064_auto_20240816_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('6dcea6fd-7329-4cf3-8449-ebd117e79a86'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='load_extension_date',
            field=models.DateTimeField(),
        ),
    ]
