# Generated by Django 3.1.4 on 2024-08-16 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0065_auto_20240816_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('ca7cfd92-deb2-411e-8277-8b80b600a9a8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='load_extension_date',
            field=models.DateTimeField(null=True),
        ),
    ]
