# Generated by Django 3.1.4 on 2024-08-16 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0066_auto_20240816_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('c16ad2d2-ecff-4776-ae0c-3de431442eff'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='load_extension_date',
            field=models.DateTimeField(default='9999-09-09'),
        ),
    ]
