# Generated by Django 3.1.4 on 2024-08-16 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0067_auto_20240816_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('ac7660d4-067b-426d-a874-ae15047c6209'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='load_extension_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
