# Generated by Django 6.0.2 on 2026-02-21 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('crm_leads', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('quote_number', models.CharField(max_length=50, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('negotiating', 'Negotiating'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('system_size', models.DecimalField(decimal_places=2, help_text='kW', max_digits=5)),
                ('panel_type', models.CharField(max_length=100)),
                ('panel_count', models.IntegerField()),
                ('inverter_type', models.CharField(max_length=100)),
                ('mounting_type', models.CharField(max_length=100)),
                ('warranty_years', models.IntegerField(default=5)),
                ('estimated_generation', models.IntegerField(help_text='kWh/year')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subsidy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('roi', models.DecimalField(decimal_places=2, help_text='%', max_digits=5)),
                ('payback_years', models.DecimalField(decimal_places=1, max_digits=4)),
                ('monthly_emi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_savings', models.DecimalField(decimal_places=2, help_text='Estimated monthly savings', max_digits=10)),
                ('valid_until', models.DateField()),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('negotiation_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('customer_approved', models.BooleanField(default=False)),
                ('internal_approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='crm_leads.lead')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation', to='surveys.survey')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
