# Generated by Django 5.2.10 on 2026-01-21 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_barcodes', '0002_barcodeimage_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodeimage',
            name='AssignBy',
            field=models.IntegerField(db_column='assignby', default=0),
        ),
        migrations.AlterField(
            model_name='barcodeimage',
            name='AssignTo',
            field=models.ForeignKey(db_column='assignto_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='barcodeimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inverterimage',
            name='AssignBy',
            field=models.IntegerField(db_column='assignby', default=0),
        ),
        migrations.AlterField(
            model_name='inverterimage',
            name='AssignTo',
            field=models.ForeignKey(db_column='assignto_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inverterimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
