# Generated by Django 5.1.3 on 2025-10-26 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("c04d280c-7a33-43fc-a6b5-7be094ca97c0"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
