# Generated by Django 5.1.3 on 2025-10-26 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("39a53acb-dcc1-4101-b253-b0f3ee4cb051"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
