# Generated by Django 5.1.3 on 2025-11-22 07:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("8006ace1-16b5-49f7-bb5b-53886ab2e59e"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
