# Generated by Django 5.1.3 on 2025-11-22 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("8df92052-49bd-462e-8511-9aeca2bfed61"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
