# Generated by Django 5.1.3 on 2025-11-29 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("b2762f43-6303-47ea-bdd9-b617d1a9b3e3"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
