# Generated by Django 5.1.3 on 2025-11-29 06:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0012_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("45cd345f-822b-476b-ae3e-40f502fb99bf"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
