# Generated by Django 5.1.3 on 2025-11-29 06:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InverterCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="OtherItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlantCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacity",
                    models.DecimalField(decimal_places=2, max_digits=6, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolarPanelCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TermsAndCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("has_yellow_background", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Representative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "unique_together": {("name", "contact")},
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consumer_type",
                    models.CharField(
                        choices=[
                            ("Residential", "Residential"),
                            ("Commercial", "Commercial"),
                            ("Industrial", "Industrial"),
                            ("Government", "Government"),
                        ],
                        default="Residential",
                        max_length=20,
                    ),
                ),
                (
                    "dc_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="DC Capacity (kWp)",
                    ),
                ),
                (
                    "ac_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="AC Capacity (kWh)",
                    ),
                ),
                ("system_na", models.BooleanField(default=False, verbose_name="N.A.")),
                (
                    "title",
                    models.CharField(
                        choices=[("Mr", "Mr"), ("Ms", "Ms")],
                        default="Mr",
                        max_length=10,
                    ),
                ),
                ("consumer_name", models.CharField(max_length=255)),
                ("consumer_address1", models.CharField(blank=True, max_length=255)),
                ("consumer_address2", models.CharField(blank=True, max_length=255)),
                ("consumer_no", models.CharField(blank=True, max_length=50)),
                ("consumer_mobile", models.CharField(blank=True, max_length=20)),
                ("quotation_no", models.CharField(blank=True, max_length=20)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("employee_name", models.CharField(blank=True, max_length=255)),
                ("panel_qty", models.IntegerField(default=0)),
                ("inverter_qty", models.IntegerField(default=0)),
                ("panel_type", models.CharField(blank=True, max_length=100)),
                ("panel_capacity_watt", models.CharField(blank=True, max_length=100)),
                (
                    "inv_phase",
                    models.CharField(
                        choices=[
                            ("Single Phase", "Single Phase"),
                            ("Three Phase", "Three Phase"),
                        ],
                        default="1 Phase",
                        max_length=13,
                    ),
                ),
                (
                    "inv_capacity_kw",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.30"), max_digits=6
                    ),
                ),
                ("panel_company_names", models.TextField(blank=True)),
                ("inverter_company_names", models.TextField(blank=True)),
                (
                    "panel_manufacturing_warranty",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "panel_performance_warranty",
                    models.CharField(blank=True, max_length=50),
                ),
                ("inverter_warranty", models.CharField(blank=True, max_length=50)),
                ("other_details", models.TextField(blank=True)),
                (
                    "structure_type",
                    models.CharField(
                        choices=[
                            ("GI Structure", "GI Structure"),
                            ("Tin Shade", "Tin Shade"),
                            ("MS Structure", "MS Structure"),
                        ],
                        default="GI Structure",
                        max_length=50,
                    ),
                ),
                (
                    "structure_back_height_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "structure_front_height_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "structure_warranty",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "special_discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "gst_5_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=10
                    ),
                ),
                (
                    "gst_18_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("18.00"), max_digits=10
                    ),
                ),
                (
                    "gst_5_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "gst_18_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("representative_names", models.TextField(blank=True)),
                ("terms_conditions_text", models.TextField(blank=True)),
                (
                    "inverter_companies",
                    models.ManyToManyField(blank=True, to="quotation.invertercompany"),
                ),
                (
                    "plant_capacity_kw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quotation.plantcapacity",
                    ),
                ),
                (
                    "representatives",
                    models.ManyToManyField(blank=True, to="quotation.representative"),
                ),
                (
                    "panel_companies",
                    models.ManyToManyField(
                        blank=True, to="quotation.solarpanelcompany"
                    ),
                ),
                (
                    "terms_conditions",
                    models.ManyToManyField(
                        blank=True, to="quotation.termsandcondition"
                    ),
                ),
            ],
        ),
    ]
