# Generated by Django 5.2.10 on 2026-01-21 15:27

import quotation.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='system_na',
            field=quotation.models.BitVaryingBooleanField(default=False, verbose_name='N.A.'),
        ),
    ]
