# Generated by Django 5.2.10 on 2026-01-31 08:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_alter_quotation_system_na'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='electricity_unit_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('11.00'), max_digits=10, verbose_name='Electricity Unit Rate (₹/kWh)'),
        ),
    ]
