# Generated by Django 5.2.10 on 2026-02-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_alter_quotation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='consumer_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email ID'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='consumer_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project_type',
            field=models.CharField(blank=True, choices=[('RoofTop', 'RoofTop'), ('Ground Mount PV', 'Ground Mount PV'), ('Street Light', 'Street Light'), ('Water Pump', 'Water Pump'), ('Hi-Mas', 'Hi-Mas'), ('Other', 'Other')], max_length=50, verbose_name='Project Type'),
        ),
    ]
