# Generated by Django 5.2.10 on 2026-02-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_quotation_consumer_email_quotation_consumer_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='hybrid_mode',
            field=models.CharField(blank=True, choices=[('UPI + Cash', 'UPI + Cash'), ('UPI + Net Banking', 'UPI + Net Banking'), ('UPI + BANK CHECK', 'UPI + BANK CHECK')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Net Banking', 'Net Banking'), ('UPI', 'UPI'), ('Cash', 'Cash'), ('Hybrid', 'Hybrid'), ('Check', 'Check')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Full Payment', 'Full Payment'), ('Part Payment', 'Part Payment'), ('Part payment & remaning payment after subsidy', 'Part payment & remaning payment after subsidy')], max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='po_order_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
