# Generated by Django 5.2.10 on 2026-02-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_quotation_hybrid_mode_quotation_is_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='hybrid_mode',
        ),
        migrations.AddField(
            model_name='quotation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='hybrid_type',
            field=models.CharField(blank=True, choices=[('UPI + Cash', 'UPI + Cash'), ('UPI + Net Banking', 'UPI + Net Banking'), ('UPI + Bank Check', 'UPI + Bank Check')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Full Payment', 'Full Payment'), ('Part Payment', 'Part Payment'), ('Part Payment & Remaining After Subsidy', 'Part Payment & Remaining Payment After Subsidy')], max_length=50, null=True),
        ),
    ]
