# Generated by Django 5.2.10 on 2026-02-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_remove_quotation_hybrid_mode_quotation_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='hybrid_type',
        ),
        migrations.AddField(
            model_name='quotation',
            name='hybrid_mode',
            field=models.CharField(blank=True, choices=[('UPI + Cash', 'UPI + Cash'), ('UPI + Net Banking', 'UPI + Net Banking'), ('UPI + BANK CHECK', 'UPI + BANK CHECK')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Full Payment', 'Full Payment'), ('Part Payment', 'Part Payment'), ('Part payment & remaning payment after subsidy', 'Part payment & remaning payment after subsidy')], max_length=80, null=True),
        ),
    ]
