# Generated by Django 5.2.10 on 2026-02-09 15:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_remove_quotation_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='inv_capacity_kw',
            field=models.DecimalField(decimal_places=2, default=Decimal('3'), max_digits=6),
        ),
    ]
