# Generated by Django 5.2.10 on 2026-02-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0012_alter_quotation_inv_capacity_kw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='inv_capacity_kw',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
