# Generated by Django 5.2.10 on 2026-02-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0013_alter_quotation_inv_capacity_kw'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='convert_consumer',
            field=models.BooleanField(default=False),
        ),
    ]
