# Generated by Django 4.1.5 on 2023-04-23 05:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('159c3762-3fb0-4f0e-95de-b5b58cac215c'), primary_key=True, serialize=False),
        ),
    ]
