# Generated by Django 4.1.5 on 2023-04-23 05:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('beb8b1b6-27a4-4755-982b-27a73bbdcd4d'), primary_key=True, serialize=False),
        ),
    ]
