# Generated by Django 4.1.5 on 2023-04-23 05:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('2dd844d5-9c29-4c4b-9637-e2ba80a9d972'), primary_key=True, serialize=False),
        ),
    ]
