# Generated by Django 6.0.2 on 2026-02-21 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('criteria', models.CharField(choices=[('electricity_bill', 'Electricity Bill (₹)'), ('property_type', 'Property Type'), ('roof_type', 'Roof Type'), ('location', 'Location (City)'), ('source', 'Lead Source'), ('age', 'Lead Age (days)')], max_length=50)),
                ('condition', models.CharField(choices=[('gt', 'Greater Than'), ('lt', 'Less Than'), ('eq', 'Equals'), ('contains', 'Contains'), ('in', 'In List (comma-separated)')], max_length=20)),
                ('value', models.CharField(help_text='Value to compare against', max_length=200)),
                ('points', models.IntegerField(help_text='Points awarded when rule matches')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='LostReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'unique_together': {('organization', 'key')},
            },
        ),
    ]
