# Generated by Django 6.0.2 on 2026-02-21 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('business_type', models.CharField(choices=[('sole', 'Sole Proprietor'), ('partnership', 'Partnership'), ('llp', 'LLP'), ('pvt', 'Pvt Ltd'), ('ltd', 'Public Ltd'), ('ngo', 'NGO'), ('other', 'Other')], max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('gst_number', models.CharField(blank=True, max_length=50)),
                ('pan_tax_id', models.CharField(blank=True, max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('logo', models.ImageField(blank=True, upload_to='org_logos/')),
                ('digital_signature', models.ImageField(blank=True, upload_to='org_signatures/')),
                ('company_stamp', models.ImageField(blank=True, upload_to='org_stamps/')),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('subdomain', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('max_users', models.IntegerField(default=5)),
                ('max_storage_mb', models.IntegerField(default=100)),
                ('api_rate_limit', models.IntegerField(default=60)),
                ('leads_limit', models.IntegerField(default=100, help_text='Maximum number of leads allowed')),
                ('quotations_limit', models.IntegerField(default=50, help_text='Maximum number of quotations allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('view_platform_dashboard', 'Can view platform dashboard'), ('manage_organizations', 'Can create/suspend/edit organizations'), ('manage_subscriptions', 'Can manage subscription plans and assignments'), ('view_all_organizations_data', "Can view any organization's data")],
                'indexes': [models.Index(fields=['subdomain'], name='core_organi_subdoma_20d032_idx'), models.Index(fields=['is_active', 'created_at'], name='core_organi_is_acti_262f0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('followup', 'Follow-up Due'), ('lead', 'New Lead'), ('stage', 'Stage Changed'), ('quotation', 'Quotation Sent'), ('survey', 'Survey Scheduled'), ('revenue', 'Revenue Recorded')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_tenant_admin', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, help_text='Job title', max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
