# Generated by Django 6.0.2 on 2026-04-03 13:49

from django.db import migrations
from django.utils import timezone
from datetime import timedelta

def add_default_data(apps, schema_editor):
    Organization = apps.get_model('core', 'Organization')
    LeadSource = apps.get_model('crm_leads', 'LeadSource')
    Campaign = apps.get_model('crm_leads', 'Campaign')
    PipelineStage = apps.get_model('pipeline', 'PipelineStage')
    LostReason = apps.get_model('settings', 'LostReason')
    ScoringRule = apps.get_model('settings', 'ScoringRule')

    for org in Organization.objects.all():
        # Lead Sources
        sources = ["Website", "Facebook Ads", "Instagram Ads", "Google Ads",
                   "WhatsApp", "JustDial", "IndiaMART", "Referral",
                   "Direct Walk-in", "Call Center", "Other"]
        for name in sources:
            LeadSource.objects.get_or_create(organization=org, name=name, defaults={'cost_per_lead': 0, 'is_active': True})

        # Campaigns
        campaigns = ["General Campaign", "Festive Offer Campaign", "Subsidy Awareness Campaign",
                     "Commercial Solar Campaign", "Residential Solar Campaign", "Referral Campaign"]
        default_source = LeadSource.objects.filter(organization=org, name="Website").first()
        for name in campaigns:
            Campaign.objects.get_or_create(
                organization=org,
                name=name,
                defaults={
                    'source': default_source,
                    'start_date': timezone.now().date(),
                    'end_date': timezone.now().date() + timedelta(days=365),
                    'budget': 0,
                    'is_active': True
                }
            )

        # Lead Stages
        stages = [
            ("New Lead", 10, "#0d6efd"),
            ("Contacted", 20, "#6c757d"),
            ("Qualified", 30, "#198754"),
            ("Site Visit Scheduled", 40, "#0dcaf0"),
            ("Survey Done", 50, "#ffc107"),
            ("Quotation Sent", 60, "#fd7e14"),
            ("Negotiation", 75, "#6f42c1"),
            ("Token Paid", 90, "#20c997"),
            ("Won", 100, "#198754"),
            ("Lost", 0, "#dc3545"),
        ]
        for order, (name, prob, color) in enumerate(stages, start=1):
            PipelineStage.objects.get_or_create(
                organization=org,
                name=name,
                defaults={'order': order, 'probability': prob, 'color': color, 'is_active': True}
            )

        # Lost Reasons
        reasons = ["Price Too High", "Chose Competitor", "No Budget", "Not Interested",
                   "No Subsidy", "Technical Not Feasible", "Delayed Decision",
                   "Wrong Lead", "Duplicate Lead", "Other"]
        for order, name in enumerate(reasons, start=1):
            LostReason.objects.get_or_create(organization=org, name=name, defaults={'order': order, 'is_active': True})

        # Scoring Rules
        rules = [
            ("electricity_bill", "gt", "5000", 20),
            ("electricity_bill", "gt", "10000", 30),
            ("property_type", "eq", "commercial", 25),
            ("property_type", "eq", "residential", 10),
            ("budget", "gt", "0", 15),
        ]
        for criteria, condition, value, points in rules:
            ScoringRule.objects.get_or_create(
                organization=org,
                criteria=criteria,
                condition=condition,
                value=value,
                defaults={'points': points, 'is_active': True}
            )

def reverse_default_data(apps, schema_editor):
    # Optional: you can delete added data, but not needed
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),  # Replace with the last migration of core
        ('crm_leads', '0001_initial'),          # Replace with the last migration of leads
        ('pipeline', '0001_initial'),       # Replace with the last migration of pipeline
        ('settings', '0001_initial'),       # Replace with the last migration of settings
    ]

    operations = [
        migrations.RunPython(add_default_data, reverse_default_data),
    ]