# Generated by Django 5.1 on 2024-10-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
