# Generated by Django 5.1 on 2024-11-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_favoritelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
