# Generated by Django 5.1 on 2024-11-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_favoritelist_created_at_favoritelist_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritelist',
            name='user',
        ),
    ]
