# Generated by Django 5.1 on 2024-11-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_favoritelist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
