# Generated by Django 5.2.10 on 2026-04-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_leads_l_stage_4bd3a6_idx',
            old_name='leads_lead_stage_4b0a5d_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_leads_l_assigne_db4415_idx',
            old_name='leads_lead_assigne_3f8857_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_leads_l_created_0dcfd2_idx',
            old_name='leads_lead_created_f7be6b_idx',
        ),
    ]
