# Generated by Django 5.1.3 on 2025-10-26 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("717edab5-0b56-4b02-a588-152c0063c799"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
