# Generated by Django 5.1.3 on 2025-10-27 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("c99e31b3-4f0c-49c4-a97b-33e8ab32c228"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
