# Generated by Django 5.1.3 on 2025-11-22 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("93547011-0359-4a2b-befe-f2e2e64a59f2"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
