# Generated by Django 5.1.3 on 2025-11-22 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("12c0aad9-c0b7-4d71-9c22-c383410e6eb2"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
