# Generated by Django 5.1.3 on 2025-11-22 08:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("2db953ad-ab52-46d7-8c69-bd6d13aa730b"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
