# Generated by Django 5.1.3 on 2025-11-29 06:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0013_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("9f86c9ba-14ce-4157-a207-281871b3d6ad"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
