# Generated by Django 5.1.3 on 2025-12-08 16:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0014_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("1ce03c52-5e16-4bb7-a0cb-b229c7146ebd"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
