# Generated by Django 5.1.3 on 2026-01-02 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0015_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("23ee5016-2b98-4e6e-a45c-42ee3da8a673"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
