# Generated by Django 5.1.3 on 2026-01-02 15:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0016_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("0fedaed0-75d1-409b-91b8-5ed6c1e5fba4"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
