# Generated by Django 5.1.3 on 2026-01-03 10:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0017_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Cust_id",
            field=models.IntegerField(
                default=uuid.UUID("18090fca-cdd8-45c8-a75d-3dfcaceb6582"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
