# Generated by Django 5.2.10 on 2026-01-21 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_customer_cust_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='AssignBy',
            field=models.ForeignKey(db_column='assignby_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fillup_By_controller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controller',
            name='AssignTo',
            field=models.ForeignKey(db_column='assignto_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_controller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controller',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Address',
            field=models.CharField(db_column='address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='City',
            field=models.CharField(db_column='city', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Comp_name',
            field=models.CharField(db_column='comp_name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Consumer',
            field=models.CharField(db_column='consumer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('7bc94d22-a639-4ff8-bc9e-4a579ab8055a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Cust_type',
            field=models.CharField(db_column='cust_type', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Emp_id',
            field=models.ForeignKey(db_column='emp_id_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Engg_Assign',
            field=models.ForeignKey(db_column='engg_assign_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engg_assign_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Gender',
            field=models.CharField(db_column='gender', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Pincode',
            field=models.IntegerField(db_column='pincode', default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Plant_Capacity',
            field=models.IntegerField(db_column='plant_capacity', default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='UPSC',
            field=models.CharField(db_column='upsc', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Ups_Soft',
            field=models.CharField(db_column='ups_soft', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='new_customer',
            field=models.ForeignKey(db_column='new_customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_customer_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer_technical_details',
            name='AssignBy',
            field=models.ForeignKey(db_column='assignby_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer_technical_details',
            name='AssignTo',
            field=models.ForeignKey(db_column='assignto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generationmeter',
            name='AssignBy',
            field=models.ForeignKey(db_column='assignby_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_meters_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generationmeter',
            name='CT_capacity',
            field=models.CharField(db_column='ct_capacity', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generationmeter',
            name='CT_make',
            field=models.CharField(db_column='ct_make', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generationmeter',
            name='CT_serial_no',
            field=models.CharField(db_column='ct_serial_no', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='generationmeter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='AssignBy',
            field=models.ForeignKey(db_column='assignby_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='ac_Panel_Cabling_Completed',
            field=models.BooleanField(db_column='ac_panel_cabling_completed', default=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='ac_Panel_Cabling_Reason',
            field=models.CharField(blank=True, db_column='ac_panel_cabling_reason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='ac_Panel_Cabling_Reason_other',
            field=models.CharField(blank=True, db_column='ac_panel_cabling_reason_other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='company_name',
            field=models.CharField(db_column='company_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='created_at',
            field=models.DateTimeField(db_column='created_at', null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='ct_Checkmark_other',
            field=models.CharField(blank=True, db_column='ct_checkmark_other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='ct_Completed',
            field=models.BooleanField(db_column='ct_completed', default=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='ct_Reason',
            field=models.CharField(blank=True, db_column='ct_reason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='dc_Panel_Cabling_Completed',
            field=models.BooleanField(db_column='dc_panel_cabling_completed', default=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='dc_Panel_Cabling_Reason',
            field=models.CharField(blank=True, db_column='dc_panel_cabling_reason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='dc_Panel_Cabling_Reason_other',
            field=models.CharField(blank=True, db_column='dc_panel_cabling_reason_other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='fabrication_Completed',
            field=models.BooleanField(db_column='fabrication_completed', default=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='fabrication_Reason',
            field=models.CharField(blank=True, db_column='fabrication_reason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='fabrication_Reason_other',
            field=models.CharField(blank=True, db_column='fabrication_reason_other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='gen_CT_Meters_Completed',
            field=models.BooleanField(db_column='gen_ct_meters_completed', default=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='gen_CT_Meters_Reason',
            field=models.CharField(blank=True, db_column='gen_ct_meters_reason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='gen_CT_Meters_Reason_other',
            field=models.CharField(blank=True, db_column='gen_ct_meters_reason_other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='generation_Meters_Completed',
            field=models.BooleanField(db_column='generation_meters_completed', default=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='generation_Meters_Reason',
            field=models.CharField(blank=True, db_column='generation_meters_reason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='generation_Meters_Reason_other',
            field=models.CharField(blank=True, db_column='generation_meters_reason_other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='info_Correct',
            field=models.BooleanField(db_column='info_correct', default=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='inverter_Completed',
            field=models.BooleanField(db_column='inverter_completed', default=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='inverter_Reason',
            field=models.CharField(blank=True, db_column='inverter_reason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='inverter_Reason_other',
            field=models.CharField(blank=True, db_column='inverter_reason_other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='net_Meter_Completed',
            field=models.BooleanField(db_column='net_meter_completed', default=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='net_Meter_Reason',
            field=models.CharField(blank=True, db_column='net_meter_reason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='net_Meter_Reason_other',
            field=models.CharField(blank=True, db_column='net_meter_reason_other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='overall_Details',
            field=models.TextField(blank=True, db_column='overall_details', null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='pipeline_Completed',
            field=models.BooleanField(db_column='pipeline_completed', default=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='pipeline_Reason',
            field=models.CharField(blank=True, db_column='pipeline_reason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='pipeline_Reason_other',
            field=models.CharField(blank=True, db_column='pipeline_reason_other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='rolling_Completed',
            field=models.BooleanField(db_column='rolling_completed', default=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='rolling_Reason',
            field=models.CharField(blank=True, db_column='rolling_reason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='rolling_Reason_other',
            field=models.CharField(blank=True, db_column='rolling_reason_other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='ropeway_Completed',
            field=models.BooleanField(db_column='ropeway_completed', default=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='ropeway_Reason',
            field=models.CharField(blank=True, db_column='ropeway_reason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='ropeway_Reason_other',
            field=models.CharField(blank=True, db_column='ropeway_reason_other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='solar_Module_Completed',
            field=models.BooleanField(db_column='solar_module_completed', default=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='solar_Module_Reason',
            field=models.CharField(blank=True, db_column='solar_module_reason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='solar_Module_Reason_other',
            field=models.CharField(blank=True, db_column='solar_module_reason_other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='walkway_Completed',
            field=models.BooleanField(db_column='walkway_completed', default=False),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='walkway_Reason',
            field=models.CharField(blank=True, db_column='walkway_reason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiondetail',
            name='walkway_Reason_other',
            field=models.CharField(blank=True, db_column='walkway_reason_other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='Comp_name',
            field=models.CharField(db_column='comp_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='meters',
            name='AssignBy',
            field=models.ForeignKey(db_column='assignby_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meters_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meters',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mseb',
            name='AssignBy',
            field=models.ForeignKey(db_column='assignby_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MSEB_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result',
            name='AssignTo',
            field=models.ForeignKey(db_column='assignto_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_userid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solarpump',
            name='AssignBy',
            field=models.ForeignKey(db_column='assignby_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fillup_By', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solarpump',
            name='AssignTo',
            field=models.ForeignKey(db_column='assignto_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solarpump',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
