# Generated by Django 5.2.10 on 2026-01-21 06:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_alter_controller_assignby_alter_controller_assignto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('d7ebc532-67b3-4b1e-8557-e33982749d7c'), primary_key=True, serialize=False),
        ),
    ]
