# Generated by Django 5.2.10 on 2026-01-21 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('89b0c62e-e97e-4f46-9407-5197ef729768'), primary_key=True, serialize=False),
        ),
    ]
