# Generated by Django 5.2.10 on 2026-01-21 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('f1390efb-5aab-4148-8794-6d69c9683e80'), primary_key=True, serialize=False),
        ),
    ]
