# Generated by Django 5.2.10 on 2026-01-21 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('6629f779-7c61-4caf-99a1-42dea45e4628'), primary_key=True, serialize=False),
        ),
    ]
