# Generated by Django 5.2.10 on 2026-01-21 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('89211bae-2496-4cc3-a1ee-156d5c66c132'), primary_key=True, serialize=False),
        ),
    ]
