# Generated by Django 5.2.10 on 2026-01-22 08:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('c8ed0df2-e624-4f9a-a158-04e5c73c964b'), primary_key=True, serialize=False),
        ),
    ]
