# Generated by Django 5.2.10 on 2026-01-22 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('e52352c3-1f58-4417-990d-f42195ea761d'), primary_key=True, serialize=False),
        ),
    ]
