# Generated by Django 5.2.10 on 2026-01-22 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('97c3077a-083d-4702-85d4-5b629a691869'), primary_key=True, serialize=False),
        ),
    ]
