# Generated by Django 5.2.10 on 2026-01-22 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('e1e9a001-38ad-46c9-bbdc-1df92318b0d9'), primary_key=True, serialize=False),
        ),
    ]
