# Generated by Django 5.2.10 on 2026-01-22 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('6fb3c7b7-9a6a-43c1-afe6-c5f6cf6a86ce'), primary_key=True, serialize=False),
        ),
    ]
