# Generated by Django 5.2.10 on 2026-01-22 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('09d51590-7259-4192-94a5-e52343ab7efe'), primary_key=True, serialize=False),
        ),
    ]
