# Generated by Django 5.2.10 on 2026-01-22 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('b10de790-6c9d-4553-b18a-d9c1b82be83b'), primary_key=True, serialize=False),
        ),
    ]
