# Generated by Django 5.2.10 on 2026-01-22 15:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('9a35c71d-2a62-4dda-87b5-0e62e960e470'), primary_key=True, serialize=False),
        ),
    ]
