# Generated by Django 5.2.10 on 2026-01-22 15:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('bcc05d7c-0a8a-4a8a-94dd-dab8c4a434e4'), primary_key=True, serialize=False),
        ),
    ]
