# Generated by Django 5.2.10 on 2026-01-22 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('7fd35f87-3f59-4f40-8422-3e6a0a5f1ca3'), primary_key=True, serialize=False),
        ),
    ]
