# Generated by Django 5.2.10 on 2026-01-22 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('e727dd81-e130-4f47-b392-070640bf2c97'), primary_key=True, serialize=False),
        ),
    ]
