# Generated by Django 5.2.10 on 2026-01-22 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('2ebbcf1a-1d27-4cdd-8c0b-e453b55f008e'), primary_key=True, serialize=False),
        ),
    ]
