# Generated by Django 5.2.10 on 2026-01-22 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('cd06e8ab-0313-43bd-b4cb-95559f57654d'), primary_key=True, serialize=False),
        ),
    ]
