# Generated by Django 5.2.10 on 2026-01-22 17:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('209a9723-3cfe-4b4c-813a-d6af5fc9e429'), primary_key=True, serialize=False),
        ),
    ]
