# Generated by Django 5.2.10 on 2026-01-22 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('d13e2a1f-db86-4875-8099-c13f5107ce09'), primary_key=True, serialize=False),
        ),
    ]
