# Generated by Django 5.2.10 on 2026-01-22 18:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('4a9817e2-2183-4778-9181-cf7996564e02'), primary_key=True, serialize=False),
        ),
    ]
