# Generated by Django 5.2.10 on 2026-01-22 18:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('9d9e8e3e-213a-468f-aeb0-77943aa62bbc'), primary_key=True, serialize=False),
        ),
    ]
