# Generated by Django 5.2.10 on 2026-01-22 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0043_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('0e7a66d5-89d9-45c1-b8ad-1fe69f9571b9'), primary_key=True, serialize=False),
        ),
    ]
