# Generated by Django 5.2.10 on 2026-01-22 19:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('528a5960-545c-491e-a99f-c065d84f8cd1'), primary_key=True, serialize=False),
        ),
    ]
