# Generated by Django 5.2.10 on 2026-01-22 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('b856f912-9f17-4f54-9454-b584bda039e7'), primary_key=True, serialize=False),
        ),
    ]
