# Generated by Django 5.2.10 on 2026-01-23 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('319ba4c2-5f2f-4d0e-a055-54435d8aa495'), primary_key=True, serialize=False),
        ),
    ]
