# Generated by Django 5.2.10 on 2026-01-23 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0047_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('ab3eaf9c-8976-4675-ac70-0c87ca21b91c'), primary_key=True, serialize=False),
        ),
    ]
