# Generated by Django 5.2.10 on 2026-01-23 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0048_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('24059dd8-28c0-4301-8dfc-c457cc378b54'), primary_key=True, serialize=False),
        ),
    ]
