# Generated by Django 5.2.10 on 2026-01-23 11:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0049_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('913bed51-b3d8-457b-b3e7-33731ef8cb86'), primary_key=True, serialize=False),
        ),
    ]
