# Generated by Django 5.2.10 on 2026-01-24 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('b8baa179-02d6-4c10-bd3f-76ff8eb5ac6d'), primary_key=True, serialize=False),
        ),
    ]
