# Generated by Django 5.2.10 on 2026-01-24 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('e2b3534c-857c-4752-b5a9-7b70b63c7e46'), primary_key=True, serialize=False),
        ),
    ]
