# Generated by Django 5.2.10 on 2026-01-24 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('c1a74218-5cef-4e3c-9381-972fd92826d8'), primary_key=True, serialize=False),
        ),
    ]
