# Generated by Django 5.2.10 on 2026-01-24 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0053_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('c72674f6-58ee-4d60-a652-f15313420f3c'), primary_key=True, serialize=False),
        ),
    ]
