# Generated by Django 5.2.10 on 2026-01-24 12:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0054_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('c5305fda-bc63-428e-a431-64200682c3a7'), primary_key=True, serialize=False),
        ),
    ]
