# Generated by Django 5.2.10 on 2026-01-24 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0055_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('71e91f0d-bf90-41d1-9517-757b84c5c22e'), primary_key=True, serialize=False),
        ),
    ]
