# Generated by Django 5.2.10 on 2026-01-25 05:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0056_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('bf37603a-1398-4273-96bb-c7e2663b982c'), primary_key=True, serialize=False),
        ),
    ]
