# Generated by Django 5.2.10 on 2026-01-25 05:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0057_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('4508a32f-022b-4b31-b761-01f59d90830d'), primary_key=True, serialize=False),
        ),
    ]
