# Generated by Django 5.2.10 on 2026-01-25 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0060_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('83b231f9-d929-4994-8d99-72fe717a5d9a'), primary_key=True, serialize=False),
        ),
    ]
