# Generated by Django 5.2.10 on 2026-01-25 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0061_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('3383d2aa-6c8a-4471-a606-66f6372eace1'), primary_key=True, serialize=False),
        ),
    ]
