# Generated by Django 5.2.10 on 2026-01-26 03:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0062_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('0eef84d2-3c07-4940-b58b-1fb6644fb458'), primary_key=True, serialize=False),
        ),
    ]
