# Generated by Django 5.2.10 on 2026-01-26 03:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0063_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('d90f92fc-efb7-46d3-874a-d48b3c2dff44'), primary_key=True, serialize=False),
        ),
    ]
