# Generated by Django 5.2.10 on 2026-01-26 04:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0064_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('7b594cce-2db4-4ad8-b60d-b9c9f04bff04'), primary_key=True, serialize=False),
        ),
    ]
