# Generated by Django 5.2.10 on 2026-01-26 05:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0065_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('4474948a-00ea-4b4c-b4c0-45c0bd07b8ee'), primary_key=True, serialize=False),
        ),
    ]
