# Generated by Django 5.2.10 on 2026-01-26 05:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0066_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('a5ac6477-6536-49d6-912b-ff13d3abf913'), primary_key=True, serialize=False),
        ),
    ]
