# Generated by Django 5.2.10 on 2026-01-26 07:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0067_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('7c863a5d-45bd-4165-91a7-610fa7f5497a'), primary_key=True, serialize=False),
        ),
    ]
