# Generated by Django 5.2.10 on 2026-01-26 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0068_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('e2efec25-71df-484c-866a-d15e6e8a0ef5'), primary_key=True, serialize=False),
        ),
    ]
