# Generated by Django 5.2.10 on 2026-01-26 07:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0070_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('c5f58071-e802-4afd-9cd2-26c84a67d457'), primary_key=True, serialize=False),
        ),
    ]
