# Generated by Django 5.2.10 on 2026-01-26 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0072_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('23f86f03-6003-4768-bb0f-229f9a5204bf'), primary_key=True, serialize=False),
        ),
    ]
