# Generated by Django 5.2.10 on 2026-01-26 12:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0074_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('68df3289-54c3-4630-bcd2-bd3635177a00'), primary_key=True, serialize=False),
        ),
    ]
