# Generated by Django 5.2.10 on 2026-01-26 12:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0075_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('16dbcdcf-ae2a-4617-b896-6f66ddb96204'), primary_key=True, serialize=False),
        ),
    ]
