# Generated by Django 5.2.10 on 2026-01-26 12:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0076_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('ccaab2f4-e1e3-4893-8fb6-d170b8352621'), primary_key=True, serialize=False),
        ),
    ]
