# Generated by Django 5.2.10 on 2026-01-26 12:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0077_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('27ede8b7-1cd9-461a-b787-5c98e9419f3e'), primary_key=True, serialize=False),
        ),
    ]
