# Generated by Django 5.2.10 on 2026-01-26 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0078_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('65652c0f-2eee-4bea-9c96-8699942098e7'), primary_key=True, serialize=False),
        ),
    ]
