# Generated by Django 5.2.10 on 2026-01-26 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0079_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('1252c85e-510b-46d2-ac06-13d49d5a1df1'), primary_key=True, serialize=False),
        ),
    ]
