# Generated by Django 5.2.10 on 2026-01-26 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0080_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('85feeb4a-a1c4-4ff6-a459-db7834462f1e'), primary_key=True, serialize=False),
        ),
    ]
