# Generated by Django 5.2.10 on 2026-01-26 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0081_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('5f1bf4b9-d7b4-4710-8c62-06d28ffd5536'), primary_key=True, serialize=False),
        ),
    ]
