# Generated by Django 5.2.10 on 2026-01-29 04:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0082_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('5b268d8b-2e67-44d6-be1b-98f14c3c2c01'), primary_key=True, serialize=False),
        ),
    ]
