# Generated by Django 5.2.10 on 2026-01-29 05:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0083_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('6f78d767-1e1e-4fd7-8fd0-b1c583f75803'), primary_key=True, serialize=False),
        ),
    ]
