# Generated by Django 5.2.10 on 2026-01-29 05:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0084_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('88b615f8-f067-4a05-9d9a-ea6452dd1045'), primary_key=True, serialize=False),
        ),
    ]
