# Generated by Django 5.2.10 on 2026-01-29 05:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0085_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('a9b82b32-aa37-4738-9182-917780ef16c2'), primary_key=True, serialize=False),
        ),
    ]
