# Generated by Django 5.2.10 on 2026-01-29 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0086_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('a804d36f-69b6-439f-930c-482ac10eae51'), primary_key=True, serialize=False),
        ),
    ]
