# Generated by Django 5.2.10 on 2026-01-29 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0087_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('b657af2c-53a5-481a-a6c7-c5a2d4a60d46'), primary_key=True, serialize=False),
        ),
    ]
