# Generated by Django 5.2.10 on 2026-01-29 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0088_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('a1e3312a-dc86-40fd-8ee7-989b276b002c'), primary_key=True, serialize=False),
        ),
    ]
