# Generated by Django 5.2.10 on 2026-01-29 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0089_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('e16f8682-d21f-40c5-8b27-534fd88a87e3'), primary_key=True, serialize=False),
        ),
    ]
