# Generated by Django 5.2.10 on 2026-01-31 05:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0090_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('ed6f78f0-31a9-4c8e-93ab-cb29ea36f607'), primary_key=True, serialize=False),
        ),
    ]
