# Generated by Django 5.2.10 on 2026-01-31 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0091_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('a514652b-8114-4c15-bf94-61141eaec8d9'), primary_key=True, serialize=False),
        ),
    ]
