# Generated by Django 5.2.10 on 2026-01-31 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0092_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('1ed1055a-46e7-4fb1-9aeb-a569787ee4d2'), primary_key=True, serialize=False),
        ),
    ]
