# Generated by Django 5.2.10 on 2026-01-31 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0093_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('c61e18df-fe42-413a-9b01-b6c9d60fad28'), primary_key=True, serialize=False),
        ),
    ]
