# Generated by Django 5.2.10 on 2026-01-31 10:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0094_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('a0603813-4e4d-4520-a2f6-f4da9c7ab1c1'), primary_key=True, serialize=False),
        ),
    ]
