# Generated by Django 5.2.10 on 2026-01-31 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0095_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('939abe60-a6ec-433a-92bf-7ac4154ee3ed'), primary_key=True, serialize=False),
        ),
    ]
