# Generated by Django 5.2.10 on 2026-02-02 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0096_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('c2a21b11-c22b-4bf6-957b-b879770f2728'), primary_key=True, serialize=False),
        ),
    ]
