# Generated by Django 5.2.10 on 2026-02-03 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0097_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('bf676121-32be-42dd-85b0-499bee3dff43'), primary_key=True, serialize=False),
        ),
    ]
