# Generated by Django 5.2.10 on 2026-02-03 05:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0099_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('69a948f8-c93c-4b08-b240-9d48ab06eead'), primary_key=True, serialize=False),
        ),
    ]
