# Generated by Django 5.2.10 on 2026-02-03 05:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0100_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('337ce9b8-ab90-4c74-80a5-019366d7403c'), primary_key=True, serialize=False),
        ),
    ]
