# Generated by Django 5.2.10 on 2026-02-03 06:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0101_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('15bf425d-30d4-4b45-8e26-eb428cbd9dc7'), primary_key=True, serialize=False),
        ),
    ]
