# Generated by Django 5.2.10 on 2026-02-03 06:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0102_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('052f6ee4-fbfe-472d-91bd-44428943e056'), primary_key=True, serialize=False),
        ),
    ]
