# Generated by Django 5.2.10 on 2026-02-03 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0103_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('f26f6864-53da-484c-822f-48605b5b816f'), primary_key=True, serialize=False),
        ),
    ]
