# Generated by Django 5.2.10 on 2026-02-03 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0104_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('63efbb15-0d53-48ac-a286-9e716629c75b'), primary_key=True, serialize=False),
        ),
    ]
