# Generated by Django 5.2.10 on 2026-02-06 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0105_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(db_column='cust_id', default=uuid.UUID('bc971d70-6f7b-42d9-bc3a-107a50cc98e0'), primary_key=True, serialize=False),
        ),
    ]
