# Generated by Django 5.2.10 on 2026-02-07 04:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0106_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.UUIDField(db_column='cust_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
