# Generated by Django 5.2.10 on 2026-02-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0107_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.BigAutoField(db_column='cust_id', primary_key=True, serialize=False),
        ),
    ]
