# Generated by Django 5.2.10 on 2026-03-25 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0115_fix_solarpump_controller_id_sequences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Assoc_Assign',
            field=models.ForeignKey(blank=True, db_column='assoc_assign_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assoc_assign_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
