# Generated by Django 5.1 on 2025-02-07 15:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('4135c227-1dad-412a-ad9c-28e67aa22e17'), primary_key=True, serialize=False),
        ),
    ]
