# Generated by Django 5.1.3 on 2025-10-26 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("stock_alert", models.IntegerField(default=0)),
                (
                    "gst",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("status", models.BooleanField(default=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_products",
                        to="product.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_purchased_products",
                        to="product.unit",
                    ),
                ),
                (
                    "sales",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_sold_products",
                        to="product.unit",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.subcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteListStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "favorite_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.favoritelist",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.stock",
                    ),
                ),
            ],
            options={
                "unique_together": {("favorite_list", "stock")},
            },
        ),
        migrations.AddField(
            model_name="favoritelist",
            name="stocks",
            field=models.ManyToManyField(
                through="inventory.FavoriteListStock", to="inventory.stock"
            ),
        ),
    ]
