# Generated by Django 5.1.3 on 2025-10-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "db_table": "api_project",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codename", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
                ("first_name", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "comp_name",
                    models.CharField(
                        blank=True, db_column="Comp_name", max_length=200, null=True
                    ),
                ),
                (
                    "consumer",
                    models.CharField(
                        blank=True, db_column="Consumer", max_length=100, null=True
                    ),
                ),
                ("current_load", models.IntegerField(blank=True, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "address",
                    models.CharField(
                        blank=True, db_column="Address", max_length=100, null=True
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "plant_capacity",
                    models.IntegerField(blank=True, db_column="Plant_Capacity"),
                ),
                (
                    "ups_soft",
                    models.CharField(
                        blank=True, db_column="Ups_Soft", max_length=100, null=True
                    ),
                ),
                (
                    "cust_type",
                    models.CharField(
                        blank=True, db_column="Cust_type", max_length=100, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, db_column="City", max_length=100, null=True
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.IntegerField(blank=True, null=True)),
                ("solar_comp", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "upsc",
                    models.CharField(
                        blank=True, db_column="UPSC", max_length=100, null=True
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "pincode",
                    models.IntegerField(blank=True, db_column="Pincode", null=True),
                ),
                ("phase", models.IntegerField(blank=True, null=True)),
                ("loadsancution", models.IntegerField(blank=True, null=True)),
                ("po_date", models.DateField(blank=True, null=True)),
                ("po_order", models.CharField(blank=True, max_length=50, null=True)),
                ("qunt_solar", models.IntegerField(blank=True, null=True)),
                ("qunt_inv", models.IntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, db_column="Gender", max_length=1, null=True
                    ),
                ),
                (
                    "cust_id",
                    models.AutoField(
                        db_column="Cust_id", primary_key=True, serialize=False
                    ),
                ),
                ("com_warranty", models.IntegerField(blank=True, null=True)),
                ("inv_warranty", models.IntegerField(blank=True, null=True)),
                ("sol_warranty", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "customer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerCustomerTechnicalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("meter_image", models.CharField(max_length=100)),
                ("netmeter_image", models.CharField(max_length=100)),
                ("abt_meter_image", models.CharField(max_length=100)),
                ("ct_cubic_image", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "customer_customer_technical_details",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "customer_department",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerEmpId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "customer_emp_id",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("salary", models.IntegerField()),
                ("bonus", models.IntegerField()),
                ("phone", models.IntegerField()),
                ("hire_date", models.DateField()),
            ],
            options={
                "db_table": "customer_employee",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerGenerationct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp_name", models.CharField(max_length=255)),
                ("make", models.CharField(max_length=255)),
                ("capacity", models.CharField(max_length=255)),
                ("serial_no", models.CharField(max_length=255)),
                ("required", models.BooleanField()),
            ],
            options={
                "db_table": "customer_generationct",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerGenerationmeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp_name", models.CharField(max_length=255)),
                ("make", models.CharField(max_length=255)),
                ("serial_no", models.CharField(max_length=255)),
                ("capacity", models.CharField(max_length=255)),
                (
                    "ct_make",
                    models.CharField(
                        blank=True, db_column="CT_make", max_length=255, null=True
                    ),
                ),
                (
                    "ct_capacity",
                    models.CharField(
                        blank=True, db_column="CT_capacity", max_length=255, null=True
                    ),
                ),
                (
                    "ct_serial_no",
                    models.CharField(
                        blank=True, db_column="CT_serial_no", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "customer_generationmeter",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerInspectiondetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "solar_module_completed",
                    models.BooleanField(db_column="solar_Module_Completed"),
                ),
                (
                    "solar_module_reason",
                    models.CharField(
                        blank=True,
                        db_column="solar_Module_Reason",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "solar_module_reason_other",
                    models.CharField(
                        blank=True,
                        db_column="solar_Module_Reason_other",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "inverter_completed",
                    models.BooleanField(db_column="inverter_Completed"),
                ),
                (
                    "inverter_reason",
                    models.CharField(
                        blank=True,
                        db_column="inverter_Reason",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "inverter_reason_other",
                    models.CharField(
                        blank=True,
                        db_column="inverter_Reason_other",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "net_meter_completed",
                    models.BooleanField(db_column="net_Meter_Completed"),
                ),
                (
                    "net_meter_reason",
                    models.CharField(
                        blank=True,
                        db_column="net_Meter_Reason",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "net_meter_reason_other",
                    models.CharField(
                        blank=True,
                        db_column="net_Meter_Reason_other",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("ct_completed", models.BooleanField(db_column="ct_Completed")),
                (
                    "ct_reason",
                    models.CharField(
                        blank=True, db_column="ct_Reason", max_length=255, null=True
                    ),
                ),
                (
                    "ct_checkmark_other",
                    models.CharField(
                        blank=True,
                        db_column="ct_Checkmark_other",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "generation_meters_completed",
                    models.BooleanField(db_column="generation_Meters_Completed"),
                ),
                (
                    "generation_meters_reason",
                    models.CharField(
                        blank=True,
                        db_column="generation_Meters_Reason",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "generation_meters_reason_other",
                    models.CharField(
                        blank=True,
                        db_column="generation_Meters_Reason_other",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gen_ct_meters_completed",
                    models.BooleanField(db_column="gen_CT_Meters_Completed"),
                ),
                (
                    "gen_ct_meters_reason",
                    models.CharField(
                        blank=True,
                        db_column="gen_CT_Meters_Reason",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gen_ct_meters_reason_other",
                    models.CharField(
                        blank=True,
                        db_column="gen_CT_Meters_Reason_other",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ac_panel_cabling_completed",
                    models.BooleanField(db_column="ac_Panel_Cabling_Completed"),
                ),
                (
                    "ac_panel_cabling_reason",
                    models.CharField(
                        blank=True,
                        db_column="ac_Panel_Cabling_Reason",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ac_panel_cabling_reason_other",
                    models.CharField(
                        blank=True,
                        db_column="ac_Panel_Cabling_Reason_other",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dc_panel_cabling_completed",
                    models.BooleanField(db_column="dc_Panel_Cabling_Completed"),
                ),
                (
                    "dc_panel_cabling_reason",
                    models.CharField(
                        blank=True,
                        db_column="dc_Panel_Cabling_Reason",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dc_panel_cabling_reason_other",
                    models.CharField(
                        blank=True,
                        db_column="dc_Panel_Cabling_Reason_other",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "fabrication_completed",
                    models.BooleanField(db_column="fabrication_Completed"),
                ),
                (
                    "fabrication_reason",
                    models.CharField(
                        blank=True,
                        db_column="fabrication_Reason",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "fabrication_reason_other",
                    models.CharField(
                        blank=True,
                        db_column="fabrication_Reason_other",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "walkway_completed",
                    models.BooleanField(db_column="walkway_Completed"),
                ),
                (
                    "walkway_reason",
                    models.CharField(
                        blank=True,
                        db_column="walkway_Reason",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "walkway_reason_other",
                    models.CharField(
                        blank=True,
                        db_column="walkway_Reason_other",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "pipeline_completed",
                    models.BooleanField(db_column="pipeline_Completed"),
                ),
                (
                    "pipeline_reason",
                    models.CharField(
                        blank=True,
                        db_column="pipeline_Reason",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "pipeline_reason_other",
                    models.CharField(
                        blank=True,
                        db_column="pipeline_Reason_other",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ropeway_completed",
                    models.BooleanField(db_column="ropeway_Completed"),
                ),
                (
                    "ropeway_reason",
                    models.CharField(
                        blank=True,
                        db_column="ropeway_Reason",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ropeway_reason_other",
                    models.CharField(
                        blank=True,
                        db_column="ropeway_Reason_other",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "rolling_completed",
                    models.BooleanField(db_column="rolling_Completed"),
                ),
                (
                    "rolling_reason",
                    models.CharField(
                        blank=True,
                        db_column="rolling_Reason",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "rolling_reason_other",
                    models.CharField(
                        blank=True,
                        db_column="rolling_Reason_other",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "overall_details",
                    models.TextField(
                        blank=True,
                        db_column="overall_Details",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("info_correct", models.BooleanField(db_column="info_Correct")),
            ],
            options={
                "db_table": "customer_inspectiondetail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerMeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp_name", models.CharField(db_column="Comp_name", max_length=255)),
                ("meters", models.CharField(max_length=50)),
                ("m_meters_make", models.CharField(max_length=255)),
                ("meters_capacity", models.CharField(max_length=255)),
                ("meters_serial", models.CharField(max_length=255)),
                ("meter_type", models.CharField(max_length=50)),
                ("meter_make", models.CharField(max_length=255)),
                ("meter_capacity", models.CharField(max_length=255)),
                ("meter_serial", models.CharField(max_length=255)),
                ("generation_meter_make", models.CharField(max_length=255)),
                ("generation_meter_capacity", models.CharField(max_length=255)),
                ("generation_meter_serial", models.CharField(max_length=255)),
                ("generation_ct", models.CharField(max_length=50)),
                ("generation_ct_make", models.CharField(max_length=255)),
                ("generation_ct_capacity", models.CharField(max_length=255)),
                ("generation_ct_serial", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "customer_meter",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerMeters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp_name", models.CharField(max_length=100)),
                ("make", models.CharField(max_length=100)),
                ("capacity", models.CharField(max_length=100)),
                ("serial_no", models.CharField(max_length=20)),
                ("transformer_type", models.CharField(max_length=50)),
                ("meter_type", models.CharField(max_length=50)),
                ("transformer_make", models.CharField(max_length=255)),
                ("transformer_capacity", models.CharField(max_length=255)),
                ("transformer_serial_number", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "customer_meters",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerMseb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp_name", models.CharField(max_length=255)),
                ("load_extension", models.BooleanField()),
                ("flisibility", models.BooleanField()),
                ("quotation", models.BooleanField()),
                ("sent_to_bill", models.BooleanField()),
                ("net_meter", models.BooleanField()),
                ("flexibility", models.BooleanField()),
                ("approval", models.BooleanField()),
                ("meter_testing", models.BooleanField()),
                ("agreement", models.BooleanField()),
                ("release", models.BooleanField()),
                ("installation_date", models.BooleanField()),
                ("load_extension_date", models.DateTimeField(blank=True, null=True)),
                ("flisibility_date", models.DateTimeField(blank=True, null=True)),
                ("quotation_date", models.DateTimeField(blank=True, null=True)),
                ("sent_to_bill_date", models.DateTimeField(blank=True, null=True)),
                ("net_meter_date", models.DateTimeField(blank=True, null=True)),
                ("flexibility_date", models.DateTimeField(blank=True, null=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("meter_testing_date", models.DateTimeField(blank=True, null=True)),
                ("agreement_date", models.DateTimeField(blank=True, null=True)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("installation_date_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "customer_mseb",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "customer_role",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DashboardOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "dashboard_order",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DashboardProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "dashboard_product",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DashboardStaffNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField()),
                ("status", models.IntegerField(blank=True, null=True)),
                ("read", models.BooleanField()),
                ("is_current", models.BooleanField()),
            ],
            options={
                "db_table": "dashboard_staff_notification",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DetectBarcodesBarcodeimage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode_data", models.CharField(max_length=255)),
                ("file_saved_at", models.DateTimeField()),
                ("image", models.CharField(max_length=100)),
                ("barcode_type", models.CharField(max_length=50)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("wattage", models.CharField(blank=True, max_length=50, null=True)),
                ("barcode_path", models.CharField(max_length=100)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("assignby", models.IntegerField(db_column="AssignBy")),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "detect_barcodes_barcodeimage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DetectBarcodesInverterimage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode_data", models.CharField(max_length=255)),
                ("file_saved_at", models.DateTimeField()),
                ("image", models.CharField(max_length=100)),
                ("barcode_type", models.CharField(max_length=50)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("wattage", models.CharField(blank=True, max_length=50, null=True)),
                ("barcode_path", models.CharField(max_length=100)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("assignby", models.IntegerField(db_column="AssignBy")),
            ],
            options={
                "db_table": "detect_barcodes_inverterimage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("change_message", models.TextField()),
                ("action_flag", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FirereportFirereport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        blank=True, db_column="FullName", max_length=255, null=True
                    ),
                ),
                (
                    "mobilenumber",
                    models.CharField(
                        blank=True, db_column="MobileNumber", max_length=255, null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=255, null=True
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, db_column="Message", max_length=255, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_column="Status", max_length=255, null=True
                    ),
                ),
                ("postingdate", models.DateTimeField(db_column="Postingdate")),
                (
                    "assignedtime",
                    models.CharField(
                        blank=True, db_column="AssignedTime", max_length=255, null=True
                    ),
                ),
                ("assignby", models.IntegerField(db_column="AssignBy")),
                ("account_id", models.IntegerField(db_column="Account_id")),
                (
                    "updationdate",
                    models.DateTimeField(
                        blank=True, db_column="UpdationDate", null=True
                    ),
                ),
            ],
            options={
                "db_table": "firereport_firereport",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FirereportFiretequesthistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
                ("postingdate", models.DateTimeField(db_column="postingDate")),
                ("assignby", models.IntegerField(db_column="AssignBy")),
            ],
            options={
                "db_table": "firereport_firetequesthistory",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FirereportTeams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teamname",
                    models.CharField(
                        blank=True, db_column="teamName", max_length=200, null=True
                    ),
                ),
                (
                    "teamleadername",
                    models.CharField(
                        blank=True,
                        db_column="teamLeaderName",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "teamleadmobno",
                    models.CharField(
                        blank=True, db_column="teamLeadMobno", max_length=15, null=True
                    ),
                ),
                (
                    "teammembers",
                    models.CharField(
                        blank=True, db_column="teamMembers", max_length=300, null=True
                    ),
                ),
                ("postingdate", models.DateTimeField(db_column="postingDate")),
            ],
            options={
                "db_table": "firereport_teams",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryFavoritelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "inventory_favoritelist",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryFavoritelistStocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_favoritelist_stocks",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("quantity", models.IntegerField()),
                ("is_deleted", models.BooleanField()),
                ("stock_alert", models.IntegerField()),
                ("gst", models.DecimalField(decimal_places=5, max_digits=10)),
                ("status", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "inventory_stock",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("status", models.BooleanField()),
            ],
            options={
                "db_table": "product_brand",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "short_name",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("status", models.BooleanField()),
            ],
            options={
                "db_table": "product_category",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("prod_description", models.TextField(blank=True, null=True)),
                ("stock_alert", models.IntegerField()),
                ("gst", models.DecimalField(decimal_places=5, max_digits=10)),
                ("status", models.BooleanField()),
            ],
            options={
                "db_table": "product_product",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "short_name",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("status", models.BooleanField()),
            ],
            options={
                "db_table": "product_subcategory",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_id", models.CharField(max_length=20, unique=True)),
                ("supplier_name", models.CharField(max_length=100, unique=True)),
                ("contact_person", models.CharField(max_length=100)),
                ("contact_email", models.CharField(max_length=254)),
                ("contact_phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("post_code", models.CharField(max_length=10)),
                ("gst_no", models.CharField(max_length=15)),
                ("status", models.BooleanField()),
            ],
            options={
                "db_table": "product_supplier",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("short_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "product_unit",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionsFinalbilldetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eway", models.CharField(blank=True, max_length=255, null=True)),
                ("veh", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("po", models.CharField(blank=True, max_length=255, null=True)),
                ("cgst", models.CharField(blank=True, max_length=255, null=True)),
                ("sgst", models.CharField(blank=True, max_length=255, null=True)),
                ("igst", models.CharField(blank=True, max_length=255, null=True)),
                ("cess", models.CharField(blank=True, max_length=255, null=True)),
                ("tcs", models.CharField(blank=True, max_length=255, null=True)),
                ("total", models.CharField(blank=True, max_length=255, null=True)),
                ("gst_value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gst_amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "round_off",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "transactions_finalbilldetails",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionsFinalsale",
            fields=[
                ("billno", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                ("is_deleted", models.BooleanField()),
                ("update_time", models.DateTimeField(blank=True, null=True)),
                ("return_bill", models.BooleanField()),
                ("return_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "transactions_finalsale",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionsFinalsaleitem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                ("total_quantity", models.IntegerField()),
                ("r_quantity", models.IntegerField(blank=True, null=True)),
                ("final_quantity", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "transactions_finalsaleitem",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionsPurchasebill",
            fields=[
                ("billno", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField()),
            ],
            options={
                "db_table": "transactions_purchasebill",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionsPurchasebilldetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eway", models.CharField(blank=True, max_length=255, null=True)),
                ("veh", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("po", models.CharField(blank=True, max_length=255, null=True)),
                ("cgst", models.CharField(blank=True, max_length=255, null=True)),
                ("sgst", models.CharField(blank=True, max_length=255, null=True)),
                ("igst", models.CharField(blank=True, max_length=255, null=True)),
                ("cess", models.CharField(blank=True, max_length=255, null=True)),
                ("tcs", models.CharField(blank=True, max_length=255, null=True)),
                ("total", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "final_amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                ("gst_value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gst_amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "round_off",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "transactions_purchasebilldetails",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionsPurchaseitem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "perprice",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "totalprice",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "transactions_purchaseitem",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionsPurchaseserial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serialno",
                    models.CharField(
                        blank=True, db_column="serialNo", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "transactions_purchaseserial",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionsReturnbilldetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eway", models.CharField(blank=True, max_length=255, null=True)),
                ("veh", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("po", models.CharField(blank=True, max_length=255, null=True)),
                ("cgst", models.CharField(blank=True, max_length=255, null=True)),
                ("sgst", models.CharField(blank=True, max_length=255, null=True)),
                ("igst", models.CharField(blank=True, max_length=255, null=True)),
                ("cess", models.CharField(blank=True, max_length=255, null=True)),
                ("tcs", models.CharField(blank=True, max_length=255, null=True)),
                ("total", models.CharField(blank=True, max_length=255, null=True)),
                ("gst_value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gst_amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "round_off",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "transactions_returnbilldetails",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionsReturnsale",
            fields=[
                ("billno", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                ("is_deleted", models.BooleanField()),
                ("update_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "transactions_returnsale",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionsReturnsaleitem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                ("total_quantity", models.IntegerField()),
                ("r_quantity", models.IntegerField(blank=True, null=True)),
                ("final_quantity", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "transactions_returnsaleitem",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionsSalebill",
            fields=[
                ("billno", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=12)),
                ("address", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=30)),
                ("gstin", models.CharField(max_length=255)),
                ("update_time", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField()),
            ],
            options={
                "db_table": "transactions_salebill",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionsSalebilldetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eway", models.CharField(blank=True, max_length=255, null=True)),
                ("veh", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("po", models.CharField(blank=True, max_length=255, null=True)),
                ("cgst", models.CharField(blank=True, max_length=255, null=True)),
                ("sgst", models.CharField(blank=True, max_length=255, null=True)),
                ("igst", models.CharField(blank=True, max_length=255, null=True)),
                ("cess", models.CharField(blank=True, max_length=255, null=True)),
                ("tcs", models.CharField(blank=True, max_length=255, null=True)),
                ("total", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "final_amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                ("gst_value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "round_off",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "transactions_salebilldetails",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionsSaleitem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("perprice", models.IntegerField(blank=True, null=True)),
                ("totalprice", models.IntegerField(blank=True, null=True)),
                ("r_quantity", models.IntegerField(blank=True, null=True)),
                ("total_quantity", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "transactions_saleitem",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionsSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=255, unique=True)),
                ("address", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("gstin", models.CharField(max_length=255, unique=True)),
                ("is_deleted", models.BooleanField()),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("post_code", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.BooleanField(blank=True, null=True)),
                ("supplier_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "transactions_supplier",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "user_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("dob", models.DateField(blank=True, db_column="DOB", null=True)),
                ("department", models.CharField(max_length=50)),
                ("image", models.CharField(blank=True, max_length=100, null=True)),
                ("designation", models.CharField(blank=True, max_length=50, null=True)),
                ("last_updated_by", models.PositiveIntegerField(blank=True, null=True)),
                ("workphone", models.CharField(blank=True, max_length=50, null=True)),
                ("bg", models.CharField(max_length=50)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("taluka", models.CharField(blank=True, max_length=50, null=True)),
                ("district", models.CharField(blank=True, max_length=50, null=True)),
                ("pg", models.CharField(blank=True, max_length=50, null=True)),
                ("institution", models.CharField(blank=True, max_length=50, null=True)),
                ("yop", models.DateField(blank=True, null=True)),
                ("specili", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("emraddress", models.CharField(blank=True, max_length=50, null=True)),
                ("rejoin_date", models.DateField(blank=True, null=True)),
                (
                    "rejoin_reason",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("resign_date", models.DateField(blank=True, null=True)),
                (
                    "resign_reason",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("resign_type", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "user_profile",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfilePermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "user_profile_permissions",
                "managed": False,
            },
        ),
    ]
